(function initRejectedDraftSketchNameTranslations(globalScope) {
  const registry = globalScope.RejectedDraftKoRegistry;
  registry.registerTranslations( {
    "Abe Linkin": "에이브 링킨",
    "Accessory Assassin": "액세서리 암살자",
    "Adorable Rodent": "사랑스러운 설치류",
    "Alburt": "앨버트",
    "Arthart": "아트하트",
    "Ancestral Tree": "선조의 나무",
    "Arboreal Ravager": "수목 약탈자",
    "Arnolfini Portrait (*)": "아르놀피니 초상 (*)",
    "Artistotle": "아티스토텔레스",
    "Artziri": "아트지리",
    "Awakened Paragon": "각성 파라곤",
    "Bama": "바마",
    "Bent Nail": "휘어진 못",
    "Biblical Angel (*)": "성서의 천사 (*)",
    "Bikachu": "비카츄",
    "Birth of Venus (*)": "비너스의 탄생 (*)",
    "Black Knight Helmet": "흑기사 투구",
    "Blunt Pencil": "무딘 연필",
    "Broccoli Grove": "브로콜리 숲",
    "Broken Astronaut": "부서진 우주비행사",
    "Broken Spectacles": "부러진 안경",
    "Buff Beetle": "근육 딱정벌레",
    "Burnished Wyvern": "광낸 와이번",
    "Burnt Match": "타버린 성냥",
    "Campbell's Soup (*)": "캠벨 수프 (*)",
    "Canvas Flayer": "캔버스 박피자",
    "Cat-Ear Girl": "고양이귀 소녀",
    "Ceezar": "시저",
    "Chap-line": "채플라인",
    "Charred Bust": "그을린 흉상",
    "Charry Czar": "차리 차르",
    "Chunky Norris": "청키 노리스",
    "Cider-Man": "사이더맨",
    "Cleopattern": "클레오패턴",
    "Clockwork Heart": "태엽 심장",
    "Coffee Stain": "커피 얼룩",
    "Concrete Wraith": "콘크리트 망령",
    "Contrast Crusher": "대비 분쇄자",
    "Cool S": "쿨 S",
    "Corgi Loaf": "코기 식빵",
    "Cracked Egg": "금 간 달걀",
    "Crate Toss": "상자 투척",
    "Cross-Hatch Crab": "교차 해칭 게",
    "Crumpled Golem": "구겨진 골렘",
    "Crustal Maiden": "크러스트 메이든",
    "Crystal Dragon": "수정 드래곤",
    "Curbie": "커비",
    "Curious Cat": "호기심 많은 고양이",
    "Cursed Marionette": "저주받은 꼭두각시",
    "Cyber Skull": "사이버 해골",
    "Danger Noodle": "위험한 뱀",
    "Dark Tater": "다크 테이터",
    "David (*)": "다비드 (*)",
    "Deep Diver": "심해 잠수부",
    "Degens Idle (*)": "디젠스 아이들 (*)",
    "Demon Hand": "악마의 손",
    "Draftception": "초안셉션",
    "Drowned Cliche": "익사한 클리셰",
    "Duct-Taped Banana": "테이프로 붙인 바나나",
    "Dumb Door": "멍청한 문",
    "Ed-ink-son": "에드잉크슨",
    "Edgar Raven": "에드거 레이븐",
    "El Viz": "엘 비즈",
    "Eldritch Tentacles": "섬뜩한 촉수",
    "Erased Face": "지워진 얼굴",
    "Eraser Dust Bunny": "지우개 먼지 토끼",
    "Eye Zen": "아이 젠",
    "Flayed Study": "벗겨진 습작",
    "Flicker Probe": "깜빡임 탐사체",
    "Floating Eye": "떠다니는 눈",
    "Floodseeker": "홍수추적자",
    "Flying Reptile": "날아다니는 파충류",
    "Fountain Pen Duelist": "만년필 결투가",
    "Franklyn": "프랭클린",
    "Freedraw Kahlo": "프리드로 칼로",
    "Froyd": "프로이드",
    "Garden of Earthly Delights (*)": "세속적 쾌락의 정원 (*)",
    "Gargoyle Sentinel": "가고일 파수꾼",
    "Ghost Line": "유령 선",
    "Girl with a Pearl Earring (*)": "진주 귀걸이를 한 소녀 (*)",
    "Girl with Balloon (*)": "풍선을 든 소녀 (*)",
    "Gluttonous Maw": "탐욕스러운 아가리",
    "Gothic Spire": "고딕 첨탑",
    "Graphite Glare": "흑연의 눈빛",
    "Great Wave of Kanagawa (*)": "가나가와의 거대한 파도 (*)",
    "Griffin Head": "그리핀 머리",
    "Grumpy Toadstools": "심술난 독버섯",
    "Guillotine": "단두대",
    "Hatch-Wolf": "해치 늑대",
    "Haunted Metronome": "유령 들린 메트로놈",
    "Huedini": "휴디니",
    "Hyena Hulk": "하이에나 헐크",
    "Hyper-Focus Eye": "초집중 눈",
    "Imp Joker": "임프 조커",
    "Ink Blot": "잉크 얼룩",
    "Ink-Drip Stalker": "잉크방울 추적자",
    "Ink Son": "잉크 아들",
    "Iron Anvil": "쇠 모루",
    "Ironing Man": "다림질맨",
    "Itchy Go": "이치고",
    "Joan of Art": "잔 오브 아트",
    "Kahn": "칸",
    "Patchy Ken": "패치 켄",
    "Martin Leather King": "마틴 레더 킹",
    "Kit on Lava": "용암 위의 키트",
    "Lash-Bug Eye": "속눈썹 벌레 눈",
    "Lead Goblet": "납 잔",
    "Loading Bar": "로딩 바",
    "Loopy": "루피",
    "Loose Button": "헐거운 단추",
    "Mannequin": "마네킹",
    "Margin Goblin": "여백 고블린",
    "Marie Blurry": "마리 블러리",
    "Mariline": "마릴린",
    "Marker Polo": "마커 폴로",
    "Mega Pan": "메가 팬",
    "Melted Candle": "녹은 양초",
    "Milking Stool": "착유 의자",
    "Mimic Chest": "미믹 상자",
    "Miranara": "미라나라",
    "Mirror Twin": "거울 쌍둥이",
    "Mismatched Reflection": "어긋난 반사",
    "Mobius Strip": "뫼비우스 띠",
    "Mona Lisa (*)": "모나리자 (*)",
    "Motz": "모츠",
    "Muddy Elemental": "진흙 정령",
    "Napo": "나포",
    "Nascent Paragon": "초기 파라곤",
    "Nazca Hummingbird (*)": "나스카 벌새 (*)",
    "Negative Void": "네거티브 공허",
    "New Tone": "새로운 톤",
    "Night Watch (*)": "야경 (*)",
    "Off-Center Portrait": "중심이 어긋난 초상",
    "Old Guitarist": "늙은 기타리스트",
    "Omen Bird": "징조의 새",
    "Ominous Sphere": "불길한 구체",
    "Pack-Man": "팩맨",
    "Petrified Heart": "석화된 심장",
    "Phantom Armor": "유령 갑옷",
    "Pickle-Oh": "피클오",
    "Pig Face Orc": "돼지 얼굴 오크",
    "Pivoting Prowler": "회전 배회자",
    "Plague Doctor": "역병 의사",
    "Plumber": "배관공",
    "Pocket Poser": "포켓 포저",
    "Poison Dart Frog": "독화살 개구리",
    "Railgun Turret": "레일건 포탑",
    "Rigid Reptile": "뻣뻣한 파충류",
    "Rock Paper Scissors": "가위바위보",
    "Rorschach Bat": "로르샤흐 박쥐",
    "Rose Window": "장미창",
    "Rotten Fruit": "썩은 과일",
    "Rusty Mech": "녹슨 메카",
    "Sass Cake": "건방진 케이크",
    "Scorpion Mech": "전갈 메카",
    "Scratch-Plate Sentinel": "스크래치판 파수꾼",
    "Scrawl Owl": "휘갈긴 부엉이",
    "Scribble": "낙서",
    "Sea Monster": "바다 괴물",
    "Shakes": "셰익스",
    "Sharper": "샤퍼",
    "Showpen": "쇼펜",
    "Six Shooter": "식스 슈터",
    "Six-Fingered Hand": "여섯 손가락 손",
    "Slab Beast": "석판 야수",
    "Moon Tzu": "문자",
    "Soda Tab": "음료 캔 따개",
    "Spaghetti Medusa": "스파게티 메두사",
    "Spiked Shield": "가시 방패",
    "Sponge Mob": "스펀지 몹",
    "Starry Night (*)": "별이 빛나는 밤 (*)",
    "Static Steed": "정전기 군마",
    "Steam Locomotive": "증기 기관차",
    "Step Hero": "스텝 히어로",
    "Stick Knight": "졸라맨 기사",
    "Stick Ribs": "갈비 졸라맨",
    "Stipplin' Hawking": "스티플링 호킹",
    "Stonehenge (*)": "스톤헨지 (*)",
    "Storm Lantern": "폭풍 랜턴",
    "Stubby Brawler": "땅딸막한 싸움꾼",
    "Stygian Dweller": "스틱스 거주자",
    "Sub Xerox": "서브 제록스",
    "Sunflowers (*)": "해바라기 (*)",
    "Tall Squirt": "키 큰 스쿼트",
    "Tangent Hydra": "접선 히드라",
    "Tangled Earbuds": "엉킨 이어버드",
    "Tangled Spider": "엉킨 거미",
    "Tattered Scarecrow": "누더기 허수아비",
    "Teslah": "테슬라",
    "The Creation of Adam (*)": "아담의 창조 (*)",
    "The False Paragon (*)": "거짓 파라곤 (*)",
    "The Kiss (*)": "키스 (*)",
    "The Last Supper (*)": "최후의 만찬 (*)",
    "The Scream (*)": "절규 (*)",
    "The Son of Man (*)": "인간의 아들 (*)",
    "The Thinker (*)": "생각하는 사람 (*)",
    "Tiny-Head Titan": "작은 머리 거인",
    "Tockies": "토키즈",
    "Top-Heavy Brute": "상체 과중한 난폭자",
    "Nascent Paragon (Dummy)": "초기 파라곤 (더미)",
    "Awakened Paragon (Dummy)": "각성 파라곤 (더미)",
    "Transcendent Paragon (Dummy)": "초월 파라곤 (더미)",
    "The False Paragon (Dummy)": "거짓 파라곤 (더미)",
    "Transcendent Paragon": "초월 파라곤",
    "Trebuchet": "트레뷰셋",
    "Tronp": "트론프",
    "Vanishing Pointless": "사라지는 무의미점",
    "Varmint Vanguard": "해충 선봉대",
    "V-Wing Bat": "V자날개 박쥐",
    "V-윙 박쥐": "V자날개 박쥐",
    "Viking Longship": "바이킹 롱십",
    "Vinchy": "빈치",
    "Vintage Biplane": "빈티지 복엽기",
    "Viscous Blob": "끈적한 덩어리",
    "Vitruvian Man": "비트루비우스 인간",
    "Wandering Ronin": "방랑 낭인",
    "Wash-ink-ton": "워싱크턴",
    "Watermark Twain": "워터마크 트웨인",
    "Weakling": "약골",
    "Whistler's Mother (*)": "휘슬러의 어머니 (*)",
    "Wally": "월리"
}, "sketch-names");
})(typeof globalThis !== "undefined" ? globalThis : window);
