(function initRejectedDraftScrollingTipTranslations(globalScope) {
  const translations = {
    "In early game, going up to Max Victories would be VERY inefficient gameplay.": "초반에는 최대 승리까지 밀어붙이는 플레이가 매우 비효율적입니다.",
    "Accuracy directly counters an enemy's Dodge/Parry chance.": "명중은 적의 회피/쳐내기 확률에 직접 대응합니다.",
    "This tip exists to fill an empty window. Just like your weekends.": "이 팁은 빈 창을 채우려고 존재합니다. 당신의 주말처럼요.",
    "You have clicked more times today than you have blinked.": "오늘 눈을 깜빡인 횟수보다 클릭한 횟수가 더 많습니다.",
    "Turn on 'Night Light' or 'Eye Comfort' mode on your device after sunset.": "해가 진 뒤에는 기기의 '야간 모드'나 '눈 보호 모드'를 켜 두세요.",
    "Staring at a screen for too long is bad for your eyes.": "화면을 너무 오래 보는 건 눈에 좋지 않습니다.",
    "Armor Penetration reduces the enemy's effective Armor value.": "방어 관통은 적의 실질 방어력 값을 낮춥니다.",
    "This game will never be as good as Degens Idle. (the OG at kuzzigames.com, not the crappy impostor)": "이 게임은 Degens Idle만큼 좋아질 수 없습니다. (kuzzigames.com의 원조 말입니다. 조잡한 가짜 말고요.)",
    "Export your save file occasionally. Cloud saves are great, but local backups are forever.": "가끔 저장 파일을 내보내세요. 클라우드 저장도 좋지만, 로컬 백업은 영원합니다.",
    "Despite her delicious name, Spaghetti Medusa's spaghetti is not edible.": "맛있어 보이는 이름과 달리, 스파게티 메두사의 스파게티는 먹을 수 없습니다.",
    "Don't ignore the Archive; skills provide powerful bonuses.": "아카이브를 무시하지 마세요. 스킬은 강력한 보너스를 제공합니다.",
    "Don't let Quintessence Softcap intimidate you, sometimes you can push into double digit softcap exponents with ease.": "정수 소프트캡에 겁먹지 마세요. 때로는 두 자릿수 소프트캡 지수까지도 쉽게 밀 수 있습니다.",
    "I'm sure your boss believes you're working on that spreadsheet right now.": "상사는 지금 당신이 스프레드시트를 만지고 있다고 믿고 있을 겁니다.",
    "Parallel lines have so much in common. It’s a shame they’ll never meet.": "평행선은 공통점이 참 많습니다. 영원히 만나지 못한다는 게 아쉽네요.",
    "I bet you wish your bank account grew this predictably.": "통장 잔고도 이렇게 예측 가능하게 늘었으면 좋겠죠.",
    "Why did the artist go to jail? He was framed.": "예술가는 왜 감옥에 갔을까요? 누명을 썼거든요. 아니, 액자에 걸렸다고 해야 하나요.",
    "I told a joke about a blank piece of paper. It was tearable.": "빈 종이에 관한 농담을 했습니다. 찢어지게 웃기더군요.",
    "Don't forget to check out Settings. Tune the game to your liking.": "설정을 확인하는 걸 잊지 마세요. 게임을 취향에 맞게 조정할 수 있습니다.",
    "Filters at top of Gallery page can help you find hidden sketches.": "갤러리 페이지 상단의 필터는 숨겨진 스케치를 찾는 데 도움이 됩니다.",
    "Clean your keyboard. Seriously, look at it right now. It's gross.": "키보드를 청소하세요. 진심입니다. 지금 한번 보세요. 꽤 끔찍합니다.",
    "Toggling off Auto-Challenge is more efficient than retreating for farming victories.": "승리를 파밍할 때는 후퇴하는 것보다 자동 도전을 끄는 편이 더 효율적입니다.",
    "The eraser was originally called 'lead eater' before marketing teams stepped in.": "지우개는 마케팅 팀이 끼어들기 전까지 원래 '납 먹보'라고 불렸습니다.",
    "What is an artist’s favorite brand of shoe? Sketchers.": "예술가가 가장 좋아하는 신발 브랜드는? Sketchers죠.",
    "Don't hoard Quintessence too long; investing early compounds your power faster.": "정수를 너무 오래 쌓아 두지 마세요. 일찍 투자할수록 힘이 더 빠르게 불어납니다.",
    "I told my wife she was drawing her eyebrows too high. She looked surprised.": "아내에게 눈썹을 너무 높게 그렸다고 말했습니다. 정말 놀란 표정이더군요.",
    "Quintessence is only awarded when you Redraw. The more currencies you've conceptualized, the more you get.": "정수는 다시 그리기할 때만 지급됩니다. 착상으로 끌어낸 재화가 많을수록 더 많이 얻습니다.",
    "Overkill can help you be victorious over multiple of the same enemy at once.": "오버킬은 같은 적을 한 번에 여러 번 이긴 것으로 처리하는 데 도움이 됩니다.",
    "Redrawing preserves your Glossary progress, making future runs easier.": "다시 그리기를 해도 용어집 진행도는 유지되어 이후 실행이 쉬워집니다.",
    "What's brown and sticky? A stick.": "갈색이고 끈적한 건 뭘까요? 막대기입니다.",
    "The Quintessence icon in the top right corner is a shortcut to the Conceptual Synthesizer.": "오른쪽 위 정수 아이콘은 착상 합성기로 가는 바로가기입니다.",
    "I know a guy who's excellent at drawing. He has a very sketchy past.": "그림을 아주 잘 그리는 사람을 압니다. 과거가 꽤 스케치하더군요.",
    "Right sidebar can be turned off with 'Show Protocol Sidebar' setting.": "'프로토콜 사이드바 표시' 설정으로 오른쪽 사이드바를 끌 수 있습니다.",
    "Your value isn't defined by your quintessence balance.": "당신의 가치는 정수 잔액으로 정해지지 않습니다.",
    "Stuck on a sketch? Try killing the one after it first.": "어떤 스케치에서 막혔나요? 그다음 스케치를 먼저 잡아 보세요.",
    "Why don’t sculptors make good friends? They take everything for granite.": "조각가는 왜 좋은 친구가 되기 어려울까요? 모든 걸 돌처럼 받아들이거든요.",
    "Wombat poop is cube-shaped. This prevents it from rolling away.": "웜뱃의 배설물은 정육면체 모양입니다. 굴러가지 않게 하려는 구조입니다.",
    "Vitamin D supplements are crucial if you spend all day indoors gaming.": "하루 종일 실내에서 게임한다면 비타민 D 보충은 중요합니다.",
    "What do you call a painting done by a cat? A paw-trait.": "고양이가 그린 초상화는 뭐라고 부를까요? 발상화입니다.",
    "The 20-20-20 rule: Every 20 mins, look 20 feet away for 20 seconds.": "20-20-20 규칙: 20분마다 20피트 떨어진 곳을 20초 동안 보세요.",
    "The 'In Combat' floating window can be moved anywhere you want. Try dragging it.": "'전투 중' 플로팅 창은 원하는 곳으로 옮길 수 있습니다. 드래그해 보세요.",
    "Graphite: The only thing cheaper than the writing in this game.": "흑연: 이 게임의 문장력보다 싼 유일한 물건입니다.",
    "Wash your bedsheets. It's been too long.": "침대 시트를 세탁하세요. 너무 오래됐습니다.",
    "Why did the scarecrow win an award? He was outstanding in his field.": "허수아비는 왜 상을 받았을까요? 자기 밭에서 아주 뛰어났거든요.",
    "There are more fake flamingos in the world than real ones.": "세상에는 진짜 플라밍고보다 가짜 플라밍고가 더 많습니다.",
    "If you put this much effort into the gym, you'd be able to lift a real sword by now.": "이만큼 헬스장에 힘썼다면 지금쯤 진짜 검도 들 수 있었을 겁니다.",
    "Battle tab Status displays always show Buffs on the left and Debuffs on the right.": "전투 탭의 상태 표시는 항상 왼쪽에 버프, 오른쪽에 디버프를 보여줍니다.",
    "Tools are generally more important than Stat Upgrades.": "대체로 도구가 능력치 업그레이드보다 더 중요합니다.",
    "The word 'pencil' comes from the Latin 'penicillus', meaning 'little tail'.": "'pencil'이라는 단어는 '작은 꼬리'를 뜻하는 라틴어 'penicillus'에서 왔습니다.",
    "If you leave now, the numbers go up slower. Can you live with that?": "지금 나가면 숫자가 더 천천히 오릅니다. 감당할 수 있겠습니까?",
    "And the Lord said to John, 'Come forth and you shall receive eternal life.' But John came fifth and won a toaster.": "주께서 요한에게 말씀하셨습니다. '넷째로 오면 영생을 얻으리라.' 하지만 요한은 다섯째로 와서 토스터를 받았습니다.",
    "Taking a 5-minute break every hour improves focus.": "매시간 5분씩 쉬면 집중력이 좋아집니다.",
    "Fun fact: If you played a real instrument for this long, you'd still be bad at it.": "재미있는 사실: 이 시간만큼 진짜 악기를 연주했어도, 당신은 아직 못했을 겁니다.",
    "Advancing Concept Milestones is the #1 priority for progression.": "착상 마일스톤 진행은 성장의 최우선 과제입니다.",
    "By far the fastest way to progress is paying attention to the Concept Milestones.": "가장 빠르게 성장하려면 착상 마일스톤에 집중하세요.",
    "Use the Sketch hide feature early, you can always unhide all for further grinding.": "스케치 숨김 기능은 초반부터 쓰세요. 나중에 더 파밍하고 싶으면 언제든 모두 다시 표시할 수 있습니다.",
    "What do you call a really dangerous neighborhood in a sketchbook? A rough draft.": "스케치북에서 정말 위험한 동네는 뭐라고 할까요? 거친 초안입니다.",
    "Your chair height should allow your feet to rest flat on the floor.": "의자 높이는 발이 바닥에 편하게 닿도록 맞추는 게 좋습니다.",
    "I used to be an artist, but I couldn't draw a salary.": "예전엔 예술가였지만, 월급은 도저히 그려낼 수 없었습니다.",
    "Graphite is just carbon arranged in sheets. Diamond is carbon in a cage.": "흑연은 탄소가 층으로 배열된 것입니다. 다이아몬드는 탄소가 우리 안에 갇힌 형태고요.",
    "Remember to drink water.": "물 마시는 걸 잊지 마세요.",
    "'Unaffected by Decay Factor' means that scaling for this stat will not be improved by lower Decay Factor.": "'보상 감소율의 영향을 받지 않음'은 보상 감소율을 낮춰도 이 능력치의 성장 효율이 좋아지지 않는다는 뜻입니다.",
    "Upgrading ATK is usually better than HP if you can end fights fast.": "전투를 빨리 끝낼 수 있다면 보통 체력보다 공격을 올리는 편이 좋습니다.",
    "The 'two-minute rule': If it takes less than two minutes, do it now.": "'2분 규칙': 2분 안에 끝나는 일이라면 지금 하세요.",
    "Cleopatra lived closer in time to the Moon landing than to the construction of the Great Pyramid.": "클레오파트라는 대피라미드 건설 시기보다 달 착륙 시기에 더 가까운 시대를 살았습니다.",
    "Sketches look better in Normal mode. Dark mode inverts the colors of the originals.": "스케치는 일반 모드에서 더 보기 좋습니다. 다크 모드는 원본 색을 반전합니다.",
    "I tried to buy a painting, but I had no Monet.": "그림을 사려 했지만 Monet가 없었습니다. 돈도 없었고요.",
    "Don't forget to Redraw. Or do. I'm just a text box.": "다시 그리기를 잊지 마세요. 아니면 말고요. 저는 그냥 텍스트 상자니까요.",
    "Drink water before you think you're hungry. You're usually just thirsty.": "배고프다고 느끼기 전에 물부터 마셔 보세요. 보통은 그냥 목마른 겁니다.",
    "The most powerful upgrade in the game is Alt+F4. But you won't use it.": "이 게임에서 가장 강력한 업그레이드는 Alt+F4입니다. 하지만 누르진 않겠죠.",
    "Yellow pencils became standard in the 1890s to signify Chinese graphite quality.": "노란 연필은 1890년대에 중국산 흑연의 품질을 나타내기 위해 표준처럼 자리 잡았습니다.",
    "You cannot hum while holding your nose. Go ahead, try it.": "코를 막고는 콧노래를 부를 수 없습니다. 해 보세요.",
    "Struggling with a specific sketch? Check the enemy stats.": "특정 스케치가 어렵나요? 적의 능력치를 확인하세요.",
    "I used to be a banker, but I lost interest.": "예전엔 은행원이었지만, 흥미를 잃었습니다. 이자도요.",
    "Your progress is saved. Your time is still lost.": "진행도는 저장됐습니다. 시간은 여전히 사라졌고요.",
    "The order of getting Stat multipliers and Rewards does not matter.": "능력치 배율과 보상을 얻는 순서는 중요하지 않습니다.",
    "Don't go grocery shopping while hungry. You'll buy weird snacks.": "배고플 때 장 보러 가지 마세요. 이상한 간식을 사게 됩니다.",
    "The first webcam was invented at Cambridge University just to check if the coffee pot was full.": "최초의 웹캠은 케임브리지 대학교에서 커피포트가 차 있는지 확인하려고 만들어졌습니다.",
    "Before rubber erasers, people used balled-up white bread to remove graphite marks.": "고무 지우개가 나오기 전에는 뭉친 흰빵으로 흑연 자국을 지웠습니다.",
    "'Idle' is a game genre. It is also an accurate description of your ambition.": "'방치형'은 게임 장르입니다. 동시에 당신의 의욕을 정확히 설명하는 말이기도 합니다.",
    "We interrupt this dopamine loop to bring you... absolutely nothing.": "도파민 루프를 잠시 중단하고 전해드립니다... 아무것도 없습니다.",
    "Sloths can hold their breath longer than dolphins can (up to 40 minutes).": "나무늘보는 돌고래보다 숨을 더 오래 참을 수 있습니다. 최대 40분까지요.",
    "Crit Damage is useless without Crit Chance. Balance your stats wisely.": "치명타 확률이 없으면 치명타 피해는 쓸모가 없습니다. 능력치를 균형 있게 맞추세요.",
    "Why did the artist carry a pencil? In case he had to draw a weapon.": "예술가는 왜 연필을 들고 다녔을까요? 무기를 뽑아야 할 때를 대비해서요.",
    "Hemingway used to sharpen his pencils with a knife. It made him feel more like a hunter.": "헤밍웨이는 칼로 연필을 깎곤 했습니다. 사냥꾼이 된 기분이 들었다고 합니다.",
    "Eventually you will reach a point where you differentiate between pushing redraws and farming redraws.": "언젠가는 밀어붙이는 다시 그리기와 파밍용 다시 그리기를 구분해야 하는 시점이 옵니다.",
    "'One more sketch' is the lie we tell ourselves to avoid doing laundry.": "'스케치 하나만 더'는 빨래를 피하려고 스스로에게 하는 거짓말입니다.",
    "During early game ATK and HP are by far the best investments.": "초반에는 공격과 체력이 단연 최고의 투자처입니다.",
    "Don't turn your brightness down. You might see your own reflection, and nobody wants that.": "밝기를 낮추지 마세요. 자기 얼굴이 비칠 수도 있고, 아무도 그걸 원하지 않습니다.",
    "I have a fear of overly intricate elevators. I'm taking steps to avoid them.": "너무 복잡한 엘리베이터가 무섭습니다. 그래서 계단을 밟고 피하는 중입니다.",
    "You're optimizing numbers that don't exist for rewards that aren't real.": "존재하지 않는 보상을 위해 존재하지 않는 숫자를 최적화하고 있습니다.",
    "Unclench your jaw. Drop your shoulders. Take a deep breath. You're welcome.": "턱 힘을 빼세요. 어깨도 내리고요. 깊게 숨 쉬세요. 천만에요.",
    "Are you cold? Go stand in the corner. It's 90 degrees.": "춥나요? 구석에 서 보세요. 90도니까요.",
    "A jiffy is an actual unit of time: 1/100th of a second.": "jiffy는 실제 시간 단위입니다. 1초의 100분의 1입니다.",
    "Parry negates an attack and reflects a portion of the damage back.": "쳐내기는 공격을 무효화하고 피해 일부를 되돌려줍니다.",
    "A day on Venus is longer than a year on Venus. It spins very, very slowly.": "금성의 하루는 금성의 1년보다 깁니다. 아주, 아주 느리게 자전하거든요.",
    "You have killed 500 sketches. They had families. Probably stick families.": "당신은 스케치 500개를 처치했습니다. 그들에게도 가족이 있었습니다. 아마 졸라맨 가족이겠죠.",
    "Cooking a meal takes 30 minutes. Ordering delivery takes 45. Save money, cook food.": "요리는 30분이면 됩니다. 배달은 45분 걸리고요. 돈 아끼고 직접 해 드세요.",
    "How does Salvador Dali start his morning? With a bowl of sur-real.": "살바도르 달리는 아침을 어떻게 시작할까요? 초현실 한 그릇으로요.",
    "Buying upgrades won't make the pain go away. But it helps the numbers.": "업그레이드를 산다고 고통이 사라지진 않습니다. 그래도 숫자는 오릅니다.",
    "Some enemies have high Armor; look for skills that overcome defense.": "일부 적은 방어력이 높습니다. 방어를 뚫는 스킬을 찾아보세요.",
    "Call your parents. They probably miss you more than you miss this game.": "부모님께 전화하세요. 당신이 이 게임을 그리워하는 것보다 부모님이 당신을 더 그리워할 겁니다.",
    "An average pencil can draw a line 35 miles long. Your mouse has traveled further.": "평균적인 연필은 35마일 길이의 선을 그릴 수 있습니다. 당신의 마우스는 그보다 더 멀리 갔을 겁니다.",
    "Why don't scientists trust atoms? Because they make up everything.": "과학자들은 왜 원자를 믿지 않을까요? 모든 걸 지어내니까요.",
    "The glossary rarity multipliers are: scrap +1%, rough +3%, framed +10%, opus +33%, masterpiece +100%.": "용어집 등급 배율은 스크랩 +1%, 초안 +3%, 프레임 +10%, 오푸스 +33%, 걸작 +100%입니다.",
    "Offline progression works for Generators and Synthesizer. Take advantage of it overnight.": "오프라인 진행은 생성기와 합성기에 적용됩니다. 밤새 활용해 보세요.",
    "Your stats can never go below their starting values. Keep that in mind when fighting Opus sketches.": "능력치는 시작값 아래로 내려가지 않습니다. 오푸스 스케치와 싸울 때 기억해 두세요.",
    "Learn to cook one pasta dish really well. It's a survival skill.": "파스타 요리 하나쯤은 제대로 익혀 두세요. 생존 스킬입니다.",
    "What do you call a fake noodle? An impasta.": "가짜 면은 뭐라고 부를까요? 임파스타입니다.",
    "Battle Speedup charges at 1 minute every 2 hours, whether the game is open or offline.": "전투 가속은 게임을 켜 둔 상태든 오프라인이든 2시간마다 1분씩 충전됩니다.",
    "Battle Speedup runs battles at 2× speed and can store up to 10 minutes.": "전투 가속은 전투를 2배 속도로 진행하며 최대 10분까지 저장할 수 있습니다.",
    "While Battle Speedup is active, flee penalty and death recovery cooldowns are cut in half.": "전투 가속이 활성화된 동안 도망 패널티와 부활 대기시간이 절반으로 줄어듭니다.",
    "Blinking is voluntary. Do it now.": "눈 깜빡이기는 의식적으로 할 수 있습니다. 지금 하세요.",
    "Congratulations, you made a number go up. Your ancestors hunting mammoths are proud.": "축하합니다. 숫자를 올렸군요. 매머드를 사냥하던 조상님들이 자랑스러워하실 겁니다.",
    "Botanically speaking, bananas are berries. Strawberries are not.": "식물학적으로 바나나는 베리입니다. 딸기는 아닙니다.",
    "Scientists are still working out how Rotten Fruit gives RGN.": "과학자들은 아직도 썩은 과일이 어떻게 RGN을 주는지 연구 중입니다.",
    "Did you hear about the kidnapping at school? It’s fine, he woke up.": "학교에서 납치 사건이 있었다는 얘기 들었나요? 괜찮습니다. 낮잠 자던 아이가 깼거든요.",
    "You could be learning a language right now. Instead, you're watching numbers go up.": "지금 언어 하나를 배우고 있을 수도 있었습니다. 대신 숫자가 오르는 걸 보고 있네요.",
    "You are just changing 0s to 1s in a JSON file. Thrilling gameplay.": "당신은 JSON 파일의 0을 1로 바꾸고 있을 뿐입니다. 정말 박진감 넘치네요.",
    "Shop notifications too annoying? Adjust the icons below level of each Stat Upgrade you want to silence.": "상점 알림이 너무 거슬리나요? 알림을 끄고 싶은 능력치 업그레이드의 레벨 아래 아이콘을 조정하세요.",
    "My pencil is broken. It's pointless to try and fix it.": "연필이 부러졌습니다. 고치려 해도 뾰족한 수가 없네요.",
    "What happens when an artist gets cold? They put on another coat.": "예술가가 추우면 어떻게 할까요? 코트를 한 겹 더 칠합니다.",
    "Bleed causes the attacker to take damage whenever they hit.": "출혈은 공격자가 타격할 때마다 피해를 받게 합니다.",
    "Stacking Freeze above 100% turns enemy healing into damage.": "빙결을 100% 넘게 쌓으면 적의 회복이 피해로 바뀝니다.",
    "Did you know that every 60 seconds a minute passes?": "60초마다 1분이 지난다는 사실, 알고 계셨나요?",
    "Resource 'Reward Exponents' in the Skill Tree are much more powerful than simple multipliers.": "스킬 트리의 재화 '보상 지수'는 단순 배율보다 훨씬 강력합니다.",
    "High enemy Armor directly reduces the healing you gain from Lifesteal.": "적의 방어력이 높으면 생명력 흡수로 얻는 회복량이 직접 줄어듭니다.",
    "Why don't skeletons fight each other? They don't have the guts.": "해골들은 왜 서로 싸우지 않을까요? 배짱이 없거든요.",
    "You are fighting sketches. Literal ink on paper. Reflect on that.": "당신은 스케치와 싸우고 있습니다. 말 그대로 종이 위 잉크입니다. 한번 곱씹어 보세요.",
    "Sometimes it can be ok to Redraw for little Quintessence just to find more rare sketches.": "더 희귀한 스케치를 찾기 위해 적은 정수만 받고 다시 그리기하는 것도 괜찮을 때가 있습니다.",
    "Listen to a podcast while grinding. It makes you feel productive by association.": "파밍하는 동안 팟캐스트를 들어 보세요. 같이 묶여서 생산적인 기분이 듭니다.",
    "Comparison is the thief of joy. Also, your stats are low.": "비교는 기쁨을 훔칩니다. 그리고 당신의 능력치는 낮습니다.",
    "Increasing Speed reduces the cooldown between your attacks.": "속도를 올리면 공격 사이의 쿨다운이 줄어듭니다.",
    "Feat Medals in Fung Shui category can be achieved by hiding sketches in the Gallery to arrange the remaining sketches in specific orders.": "풍수 카테고리의 업적 메달은 갤러리에서 스케치를 숨겨 남은 스케치를 특정 순서로 배치하면 달성할 수 있습니다.",
    "Touch grass. Actual, physical grass. It has 8K resolution.": "잔디를 만지세요. 진짜 물리적인 잔디요. 8K 해상도입니다.",
    "This text is procedurally generated to simulate a personality. It's failing, isn't it?": "이 문구는 개성을 흉내 내려고 절차적으로 생성됐습니다. 실패하고 있죠?",
    "The first recorded use of the word 'sketch' was in 1668.": "'sketch'라는 단어가 기록상 처음 쓰인 것은 1668년입니다.",
    "Graphite is a conductor of electricity. Do not stick pencils in outlets.": "흑연은 전기를 통합니다. 콘센트에 연필을 꽂지 마세요.",
    "Why did the math book look sad? Because it had too many problems.": "수학책은 왜 슬퍼 보였을까요? 문제가 너무 많았거든요.",
    "You can make the first few shop tools entirely free after a Redraw by investing in the Archive.": "아카이브에 투자하면 다시 그리기 후 첫 몇 개 상점 도구를 완전히 무료로 만들 수 있습니다.",
    "If you have to ask 'is it too late to go to bed?', the answer is always yes.": "'지금 자러 가기엔 너무 늦었나?'라고 묻고 있다면, 답은 항상 예입니다.",
    "Octopuses have three hearts. Two pump blood to the gills, one to the rest of the body.": "문어는 심장이 세 개입니다. 두 개는 아가미로, 하나는 몸 전체로 피를 보냅니다.",
    "What did the 0 say to the 8? 'Nice belt.'": "0이 8에게 뭐라고 했을까요? '벨트 멋지네.'",
    "I considered adding a 'Win' button, but that would ruin the engagement metrics.": "'승리' 버튼을 넣을까 했지만, 참여 지표가 망가질 것 같았습니다.",
    "Picasso's full name has 23 words.": "피카소의 전체 이름은 23단어입니다.",
    "John Steinbeck used up to 60 pencils a day. He would have loved auto-battle.": "John Steinbeck은 하루에 연필을 최대 60자루까지 썼습니다. 자동 전투를 꽤 좋아했을 겁니다.",
    "When skills that guarantee sketches are unlocked, selections can be made in the Glossary.": "스케치를 확정하는 스킬이 해금되면 용어집에서 선택할 수 있습니다.",
    "I am a collection of pixels judging a collection of atoms. Who is really winning?": "저는 픽셀 덩어리로서 원자 덩어리를 평가하고 있습니다. 진짜 승자는 누구일까요?",
    "Change your passwords. 'Password123' is not a security measure.": "비밀번호를 바꾸세요. 'Password123'은 보안 대책이 아닙니다.",
    "Stretch your wrists. Carpal tunnel is the real end-game boss.": "손목을 스트레칭하세요. 손목터널증후군이 진짜 엔드게임 보스입니다.",
    "Your attention span is shorter than this sen— oh, look, a shiny button.": "당신의 집중력은 이 문장보다도 짧습니— 어, 반짝이는 버튼이다.",
    "Sketching is just taking a line for a walk.": "스케치는 선을 산책시키는 일일 뿐입니다.",
    "I'm not saying you're addicted, but you just read this entire sentence.": "중독이라고 말하는 건 아닙니다. 다만 이 문장을 끝까지 읽으셨네요.",
    "Hypnotized sketches have a chance to attack themselves instead of you.": "최면에 걸린 스케치는 당신 대신 자기 자신을 공격할 확률이 있습니다.",
    "Plants need water too. Check that succulent on your desk.": "식물도 물이 필요합니다. 책상 위 다육식물을 확인하세요.",
    "Open a window. The air in your room is mostly carbon dioxide and regret.": "창문을 여세요. 방 안 공기는 대부분 이산화탄소와 후회로 차 있습니다.",
    "Please rate this game 5 stars. My developer needs validation. He's very fragile.": "이 게임에 별 5개를 주세요. 제 개발자는 인정이 필요합니다. 아주 여립니다.",
    "I'd ask how your day is going, but you're playing an idle game at 2 AM.": "하루가 어땠는지 묻고 싶지만, 새벽 2시에 방치형 게임을 하고 계시네요.",
    "Error 404: Meaning of life not found. Please continue idling.": "오류 404: 삶의 의미를 찾을 수 없습니다. 계속 방치하세요."
  };

  const labels = {
    TIP: "팁",
    "팁": "팁",
    CRITIQUE: "비평",
    "비평": "비평",
    FACT: "사실",
    "사실": "사실",
    JOKE: "농담",
    "농담": "농담",
    LPT: "생활 팁",
    "생활 팁": "생활 팁"
  };
  globalScope.REJECTED_DRAFT_KO_SCROLLING_TIP_TRANSLATIONS = translations;
  globalScope.REJECTED_DRAFT_KO_SCROLLING_TIP_LABELS = labels;
})(typeof globalThis !== "undefined" ? globalThis : window);
