(function initRejectedDraftArchiveSkillTranslations(globalScope) {
  const registry = globalScope.RejectedDraftKoRegistry;
  registry.registerTranslations( {
    "Porous Canvas": "다공성 캔버스",
    "Stencil Precision": "스텐실 정밀도",
    "Compressed Charcoal": "압축 목탄",
    "Serrated Edge": "톱니 가장자리",
    "Bold Lines": "굵은 선",
    "Defacing Property": "낙서 훼손",
    "Wax Seal": "왁스 봉인",
    "Red Spill": "붉은 번짐",
    "Solid Fill": "단단한 채우기",
    "Creative Burnout": "창작 번아웃",
    "Reaction Time": "반응 시간",
    "Precision Work": "정밀 작업",
    "Sharp Edges": "날카로운 모서리",
    "Liquid Motion": "액체 움직임",
    "Electric Dread": "전기 공포",
    "Final Touches": "마지막 손질",
    "Smudged Lines": "번진 선",
    "Delusional Optimism": "망상적 낙관",
    "Pretentious Gilding": "허세 금도금",
    "Clogged Nozzle": "막힌 노즐",
    "Thick Shading": "두꺼운 명암",
    "Thick Paper": "두꺼운 종이",
    "Exposure Therapy": "노출 요법",
    "Swirling Colors": "소용돌이 색",
    "Vampiric Touch": "흡혈의 손길",
    "Calculated Risk": "계산된 위험",
    "Steady Hand": "안정된 손",
    "Frantic Scribbling": "광란의 낙서",
    "Opaque Nonsense": "불투명한 헛소리",
    "Stubborn Refusal": "완고한 거부",
    "Bitter Aftertaste": "쓴 뒷맛",
    "Toxic Pigment": "독성 안료",
    "Indestructible Cap": "부서지지 않는 뚜껑",
    "Pyromaniac Tool": "방화광 도구",
    "Forbidden Treasure": "금지된 보물",
    "Chemical Blast": "화학 폭발",
    "Caffeine Crash": "카페인 추락",
    "Liquid Nitrogen": "액체 질소",
    "Speed Paint": "스피드 페인트",
    "Toxic Coating": "독성 코팅",
    "Cleansing Light": "정화의 빛",
    "Lethargic Ash": "무기력한 재",
    "Quick Strokes": "빠른 붓질",
    "{value}% multiplier": "{value}% 배율",
    "{value}% divider": "{value}% 속도 보정",
    "Acrylic Discount": "아크릴 할인",
    "Acrylic Generator": "아크릴 생성기",
    "Portfolio Review": "스케치 순회",
    "Standing Order": "상시 주문",
    "Auto-Challenge": "자동 도전",
    "Curator's Choice": "큐레이터의 선택",
    "Auto-Retry": "자동 재시도",
    "Basically Buddha": "거의 부처",
    "Bulk Order": "대량 주문",
    "Burnt Edges": "탄 가장자리",
    "Charcoal Generator": "목탄 생성기",
    "Charcoal Super Discount": "목탄 슈퍼 할인",
    "Clean Slate": "깨끗한 새 출발",
    "Caffeine Drip": "카페인 드립",
    "Coffee Generator": "커피 생성기",
    "Conceptual Bridge": "착상의 다리",
    "Graphite Generator": "흑연 생성기",
    "Automatically produces 0.1 Graphite per second.": "초당 흑연 0.1을 자동 생산합니다.",
    "Graphite Pump": "흑연 펌프",
    "Graphite Super Discount": "흑연 슈퍼 할인",
    "Reduces the cost of all Ink stat upgrades by 90%.": "모든 잉크 능력치 업그레이드 비용을 90% 줄입니다.",
    "Ink Thinner": "잉크 희석제",
    "Ink Generator": "잉크 생성기",
    "Marker Discount": "마커 할인",
    "Marker Generator": "마커 생성기",
    "Master Control": "마스터 제어",
    "Medal X-Ray": "메달 X-레이",
    "Photon Discount": "광자 할인",
    "Automatically produces 1 Photon per second.": "초당 광자 1을 자동 생산합니다.",
    "Portable Flashlight": "휴대용 손전등",
    "Photon Generator": "광자 생성기",
    "Pre-Battle Meditation": "전투 전 명상",
    "Precise Eraser": "정밀 지우개",
    "Randomizer": "무작위화",
    "Curator's Insight": "큐레이터의 통찰",
    "Review Audit": "순회 한도",
    "Reward Booster": "보상 부스터",
    "Rewards Filter": "보상 필터",
    "Sketch Hiding": "스케치 숨김",
    "Creative Pivot": "창의적 전환",
    "Soft Eraser": "부드러운 지우개",
    "Spray Discount": "스프레이 할인",
    "Underdog's Commission": "언더독의 의뢰",
    "Victory Lap": "승리 랩",
    "Wax Coating": "왁스 코팅",
    "Wax on Wax": "왁스 위의 왁스",
    "Acrylic Anomaly": "아크릴 변칙",
    "Essence Refinement": "정수 정제",
    "Temporal Capacity": "시간 용량",
    "Framed Victory Study": "프레임 승리 연구",
    "Opus Victory Study": "오푸스 승리 연구",
    "Paragon takes 2 slots instead of 3": "파라곤이 3칸 대신 2칸을 차지합니다",
    "Paragon Efficiency": "파라곤 효율",
    "Paragon sketches can be guaranteed": "파라곤 스케치를 확정할 수 있습니다",
    "Paragon Attainment": "파라곤 획득",
    "Extend ranking system to 1-4": "순위 시스템을 1-4까지 확장",
    "Extend ranking system to 1-5": "순위 시스템을 1-5까지 확장",
    "Extend ranking system to 1-6": "순위 시스템을 1-6까지 확장",
    "Extend ranking system to 1-9": "순위 시스템을 1-9까지 확장",
    "Manual 1-3 ranking system": "수동 1-3 순위 시스템",
    "Portfolio Prioritizer": "순회 우선순위",
    "Portfolio Prioritizer II": "순회 우선순위 II",
    "Portfolio Prioritizer III": "순회 우선순위 III",
    "Portfolio Prioritizer IV": "순회 우선순위 IV",
    "Portfolio Prioritizer V": "순회 우선순위 V",
    "Randomizer uses prioritization": "무작위화가 우선순위를 사용합니다",
    "Randomizer Prioritizer": "무작위화 우선순위",
    "Displays rarity counts in Redraw Summary": "다시 그리기 요약에 희귀도 수를 표시합니다",
    "Rarity Foresight": "희귀도 예지",
    "Curator's Insight shows #s": "큐레이터의 통찰이 숫자를 표시합니다",
    "Rarity Insight": "희귀도 통찰",
    "-0.1s redraw delay": "다시 그리기 지연 -0.1초",
    "Targeted Optimization": "타겟 최적화",
    "Auto-redraw until targets met": "목표를 만족할 때까지 자동 다시 그리기",
    "Exclude 1 rarity in exploratory redraw": "탐색 다시 그리기에서 희귀도 1개 제외",
    "Selective Explorer": "선택적 탐험가",
    "Search for new sketches": "새 스케치 검색",
    "Exploratory Redraw": "탐색 다시 그리기",
    "Instant Targeted Redraw": "즉시 타겟 다시 그리기",
    "Streamlined Search": "간소화된 검색",
    "-1% min redraw chance": "최소 다시 그리기 확률 -1%",
    "Higher Expectations": "높아진 기대치",
    "Targeted Redraw": "타겟 다시 그리기",
    "Rough Victory Study": "초안 승리 연구",
    "Automated Workflow": "자동화 워크플로",
    "Tool Presets": "도구 프리셋",
    "Temporal Overclock": "시간 오버클럭",
    "Reward Booster works on Framed sketches": "보상 부스터가 프레임 스케치에 작동합니다",
    "Framed Booster": "프레임 부스터",
    "Attack delay reduction.": "공격 지연 감소.",
    "Attack Speed Bonus": "공격 속도 보너스",
    "Multiplier for how often stat upgrades are automatically checked and purchased.": "능력치 업그레이드를 자동으로 확인하고 구매하는 빈도의 배율.",
    "Autobuy Speed": "자동 구매 속도",
    "Tools auto-enabled on redraw, starting from top of active protocols list.": "다시 그리기 시 활성 프로토콜 목록 위쪽부터 도구가 자동 활성화됩니다.",
    "Auto-Enable Tools": "도구 자동 활성화",
    "Automatically starts challenging the first available sketch after a Redraw.": "다시 그리기 후 첫 번째 도전 가능 스케치에 자동으로 도전합니다.",
    "Auto-Challenge Redraw": "다시 그리기 자동 도전",
    "Allows you to meditate on sketches even after they have reached Max Victories.": "최대 승리에 도달한 스케치에도 명상할 수 있습니다.",
    "Wait time after defeat.": "패배 후 대기 시간.",
    "Flat amount of extra victories granted by the Victory Lap tool.": "승리 랩 도구가 부여하는 추가 승리의 고정 수치.",
    "Extra Laps": "추가 랩",
    "The multiplicative base applied per purchased Feat Medal.": "구매한 업적 메달마다 적용되는 곱연산 기준값.",
    "Feat Medal Base": "업적 메달 기준값",
    "Feat Mult": "업적 배율",
    "Wait time after fleeing.": "도망 후 대기 시간.",
    "Flow State": "몰입 상태",
    "Tools unlocked on redraw, starting from top of tools list.": "다시 그리기 시 도구 목록 위쪽부터 해금되는 도구.",
    "Free Tools": "무료 도구",
    "Multiplier for all currency generators.": "모든 재화 생성기의 배율.",
    "Generator Power": "생성기 출력",
    "Inspiration Cap Bonus": "영감 상한 보너스",
    "Visible sketches ahead of last defeated sketch.": "마지막으로 격파한 스케치 이후로 보이는 스케치 수.",
    "Lookahead": "미리보기",
    "Creative Pivot works on Masterpiece rarity enemies.": "창의적 전환이 걸작 희귀도 적에게도 작동합니다.",
    "Max Speedup": "최대 가속",
    "Victory limit per sketch.": "스케치당 승리 제한.",
    "Max Victories": "최대 승리",
    "Base cooldown duration before meditating again.": "다시 명상하기 전 기본 재사용 대기시간.",
    "Meditation Cooldown": "명상 재사용 대기시간",
    "Framed+ sketches now grant 3 meditation slots.": "프레임 이상 스케치가 이제 명상 슬롯 3개를 제공합니다.",
    "Additional percentage granted when hitting the gold zone.": "골드 구간 적중 시 추가로 얻는 비율.",
    "Meditation Gold Bonus": "명상 골드 보너스",
    "Rough+ sketches now grant 2 meditation slots.": "초안 이상 스케치가 이제 명상 슬롯 2개를 제공합니다.",
    "Maximum stat percentage boost achievable via meditation.": "명상으로 얻을 수 있는 최대 능력치 비율 증가.",
    "Additional percentage granted when hitting the teal zone.": "청록 구간 적중 시 추가로 얻는 비율.",
    "Meditation Teal Bonus": "명상 청록 보너스",
    "% of excess damage used to calculate how many extra victories are granted.": "추가 승리 수 계산에 사용되는 초과 피해 비율.",
    "Overkill": "오버킬",
    "Additional uses for the Precise Eraser.": "정밀 지우개 추가 사용 횟수.",
    "Precise Eraser Uses": "정밀 지우개 사용 횟수",
    "Bonus Quintessence production for Graphite Concept in Conceptual Synthesizer.": "착상 합성기의 흑연 착상 정수 생산 보너스.",
    "Quintessence Gain": "정수 획득",
    "Quintessence Pinnacle": "정수 정점",
    "Multiplies Pending Quintessence gain based on the number of sketches that have reached their Maximum Victories during the current Redraw cycle. Boosting your Max Victories limit also provides an exponential increase to this effect. Formula: (1 + (Max Victories / 10000)) ^ (# of Maxed Sketches)": "현재 다시 그리기 주기에서 최대 승리에 도달한 스케치 수에 따라 대기 중인 정수 획득량을 배가합니다. 최대 승리 한도를 올리면 이 효과도 지수적으로 증가합니다. 공식: (1 + (최대 승리 / 10000)) ^ (최대치 도달 스케치 수)",
    "Total number of times you have redrawn the world.": "세계를 다시 그린 총 횟수.",
    "Multiplier for the Reward Booster tool.": "보상 부스터 도구의 배율.",
    "Booster Power": "부스터 출력",
    "Additional uses for the Reward Booster tool.": "보상 부스터 도구 추가 사용 횟수.",
    "Reward Booster Uses": "보상 부스터 사용 횟수",
    "Minimum attack delay (ms).": "최소 공격 지연(ms).",
    "Speed Cap": "속도 상한",
    "Additional uses for the Creative Pivot tool.": "창의적 전환 도구 추가 사용 횟수.",
    "Creative Pivot Uses": "창의적 전환 사용 횟수",
    "The time in seconds between automatic redraws when Targeted Redraw is active.": "타겟 다시 그리기가 활성화된 동안 자동 다시 그리기 사이의 시간(초).",
    "Targeted Redraw Delay": "타겟 다시 그리기 지연",
    "Time Acceleration": "시간 가속",
    "Increase the maximum accumulated Battle Speedup time.": "누적 가능한 전투 가속 최대 시간을 늘립니다.",
    "Each one takes 3 slots and must be toggled sequentially (I → II → III → IV).": "각 항목은 슬롯 3개를 차지하며 순서대로 켜야 합니다 (I → II → III → IV).",
    "Displays a breakdown of sketch rarity counts in the Redraw Summary.": "다시 그리기 요약에 스케치 희귀도 수 breakdown을 표시합니다.",
    "Booster, Eraser, and Pivot can be preset in Glossary": "부스터, 지우개, 전환을 용어집에서 미리 설정할 수 있습니다",
    "Reward Booster works on Masterpiece sketches": "보상 부스터가 걸작 스케치에 작동합니다",
    "Masterpiece Booster": "걸작 부스터",
    "Reward Booster works on Opus sketches": "보상 부스터가 오푸스 스케치에 작동합니다",
    "Opus Booster Negative effect is divided": "오푸스 부스터의 부정 효과가 나뉩니다",
    "Opus Dampener": "오푸스 감쇠기",
    "Opus Booster": "오푸스 부스터",
    "+25% Reward Booster Effect": "보상 부스터 효과 +25%",
    "Booster Overclock": "부스터 오버클럭",
    "Booster grants retroactive rewards": "부스터가 소급 보상을 지급합니다",
    "Reward Siphon": "보상 흡수",
    "+1 Reward Booster Use": "보상 부스터 사용 +1",
    "Booster Proliferation": "부스터 증식",
    "Clean Slate only removes 10% (rounded down) of Buffs": "클린 슬레이트가 버프의 10%(내림)만 제거합니다",
    "Careful Cleanse": "신중한 정화",
    "Clean Slate removes 40% (rounded up) of Debuffs": "클린 슬레이트가 디버프의 40%(올림)를 제거합니다",
    "Deep Cleanse": "깊은 정화",
    "Increases the activation chance of Clean Slate from 20% to 40%": "클린 슬레이트 발동 확률을 20%에서 40%로 늘립니다",
    "Reliable Cleanse": "믿음직한 정화",
    "+0.001 Feat Medal Base": "업적 메달 기준값 +0.001",
    "Venture Capital": "벤처 캐피털",
    "+0.005 Feat Medal Base": "업적 메달 기준값 +0.005",
    "Market Dominance": "시장 지배",
    "+0.0001 Feat Medal Base": "업적 메달 기준값 +0.0001",
    "Investment Plan": "투자 계획",
    "-0.01 Decay Factor": "보상 감소율 -0.01",
    "Lasting Impressions": "오래 남는 인상",
    "-0.1s flee penalty": "도망 패널티 -0.1초",
    "Quick Escape": "빠른 탈출",
    "-0.1s death penalty": "부활 대기 -0.1초",
    "Swift Recovery": "신속 회복",
    "+1 Lookahead": "미리보기 +1",
    "Perspective Shift": "관점 전환",
    "Okay, this is getting ridiculous": "좋아, 이건 점점 말도 안 되네",
    "All The Tools": "모든 도구",
    "Double speed of Stat Upgrade Autobuy": "능력치 업그레이드 자동 구매 속도 2배",
    "Autobuy Efficiency": "자동 구매 효율",
    "Stat Upgrades Autobuy Toggles kept on Redraw": "다시 그리기 후에도 능력치 업그레이드 자동 구매 토글 유지",
    "Autobuy Preserver": "자동 구매 보존",
    "Preserve more active protocol states": "더 많은 활성 프로토콜 상태 보존",
    "Systematic Workflow": "체계적 워크플로",
    "Purchases all skills": "모든 스킬을 구매합니다",
    "Leeroy Study": "리로이 연구",
    "Unlock Buy Max for Skill Tree": "스킬 트리 최대 구매 해금",
    "Unlocks the \"Max\" button on all skill tree nodes.": "모든 스킬 트리 노드의 \"최대\" 버튼을 해금합니다.",
    "Iterative Refinement": "반복 정제",
    "Custom % Buy for Skill Tree": "스킬 트리 사용자 지정 % 구매",
    "Finetuned Refinement": "미세 조정 정제",
    "Ready For More": "더 준비됨",
    "Allow meditation on maxed sketches": "최대치 스케치에도 명상 허용",
    "Moon Tzu says: A master never stops learning, even from a defeated foe.": "문자는 말합니다: 대가는 패배한 적에게서도 배움을 멈추지 않습니다.",
    "Even more free tools": "더 많은 무료 도구",
    "Now The Good Tools": "이제 좋은 도구",
    "Double all generators": "모든 생성기 2배",
    "Less Decay Please": "감쇠 좀 줄여줘",
    "Pivot works on Masterpiece": "전환이 걸작에 작동합니다",
    "Choose between previous and new meditation results": "이전 명상 결과와 새 결과 중 선택",
    "Contemplative Revision": "사색적 수정",
    "+1% Gold Zone Effect": "골드 구간 효과 +1%",
    "Meditation Mastery": "명상 숙련",
    "-0.5 min meditation cooldown": "명상 재사용 대기시간 -0.5분",
    "Meditation Recovery": "명상 회복",
    "Skip Meditation for Teal Zone": "청록 구간으로 명상 건너뛰기",
    "25% Gold Zone Skip Chance": "골드 구간 건너뛰기 확률 25%",
    "Gilded Certainty": "금빛 확신",
    "Quiet Certainty": "고요한 확신",
    "+1% Teal Zone Effect": "청록 구간 효과 +1%",
    "Meditation Zen": "명상 선",
    "Start with more free tools": "더 많은 무료 도구로 시작",
    "More Free Tools": "더 많은 무료 도구",
    "More Victories!": "더 많은 승리!",
    "+1 Precise Eraser Use": "정밀 지우개 사용 +1",
    "Multi-Use Eraser": "다중 사용 지우개",
    "Precise Eraser works on Masterpiece": "정밀 지우개가 걸작에 작동합니다",
    "Masterpiece Eraser": "걸작 지우개",
    "Precise Eraser works on Opus": "정밀 지우개가 오푸스에 작동합니다",
    "Opus Eraser": "오푸스 지우개",
    "+10% Overkill": "오버킬 +10%",
    "Divine Retribution": "신성한 응징",
    "+1% Overkill": "오버킬 +1%",
    "Overoverkill": "오버오버킬",
    "I don't lose. Just run out of paper.": "나는 지지 않는다. 종이가 떨어질 뿐.",
    "Professional Winner": "전문 승자",
    "+QE gain per Maxed Sketch": "최대치 스케치마다 정수 획득량 증가",
    "-1 min meditation cooldown": "명상 재사용 대기시간 -1분",
    "Rapid Meditations": "빠른 명상",
    "Surrender when Slow > 400%": "둔화가 400%를 넘으면 항복",
    "Seppuku": "할복",
    "+1 Creative Pivot Use": "창의적 전환 사용 +1",
    "Extra Inspiration": "추가 영감",
    "Temporal Flow": "시간 흐름",
    "You know the drill - more tools": "알잖아요 - 도구를 더",
    "Tool Collector": "도구 수집가",
    "Underdog's Commission applies to Photon": "언더독의 의뢰가 광자에 적용됩니다",
    "Photon Commission": "광자 의뢰",
    "Boosts Victory Lap tool": "승리 랩 도구 강화",
    "Winning!": "이기는 중!",
    "Ink Singularity": "잉크 특이점",
    "Eternal Practice": "영원한 연습",
    "Masterpiece Pivot": "걸작 전환",
    "Meditation Framing": "명상 프레이밍",
    "Meditation Prime": "명상 프라임"
}, "archive-tree-skills");
})(typeof globalThis !== "undefined" ? globalThis : window);
