(function initRejectedDraftTooltipsPatterns(globalScope) {
  const registry = globalScope.RejectedDraftKoRegistry;
  const { formatCompactNumber, t } = registry;
  const scrollingTipContext = registry.scrollingTipContext();
  const scrollingTipLabels = scrollingTipContext.labels;
  const scrollingTipTranslations = scrollingTipContext.translations;
  const scrollingTipPattern = scrollingTipContext.pattern;
  registry.registerPatterns([
    [/^(.+) Chance Chance to apply (.+)\. (.+) Values over 100% allow for multiple applications per hit\.$/, (_text, titleEffect, bodyEffect, description) => `${t(titleEffect)} 확률\n${t(bodyEffect)}을 적용할 확률입니다. ${t(description)} 100%를 넘으면 한 번의 타격에 여러 번 적용될 수 있습니다.`],
    [/^Chance to apply (.+)\.$/, (_text, effect) => `${t(effect)} 적용 확률.`],
    [/^Chance to apply (.+) to enemy\.$/, (_text, effect) => `적에게 ${t(effect)} 적용 확률.`],
    [/^Chance to gain (.+) stacks on attack\.$/, (_text, effect) => `공격 시 ${t(effect)} 중첩 획득 확률.`],
    [/^Chance to gain (.+) on attack\.$/, (_text, effect) => `공격 시 ${t(effect)} 획득 확률.`],
    [/^(Vulnerability|취약성) Multiplies damage taken from Critical Hits by ([\d.]+)\.$/, (_text, title, amount) => `${t(title)}\n치명타 피해를 ${amount}배 더 받습니다.`],
    [/^Multiplies damage taken from Critical Hits by ([\d.]+)\.$/, (_text, amount) => `치명타 피해를 ${amount}배 더 받습니다.`],
    [/^\+([\d.]+%) (.+) per level$/, (_text, amount, stat) => `레벨당 ${t(stat)} +${amount}`],
    [/^\+([\d.]+) (.+) per level$/, (_text, amount, stat) => `레벨당 ${t(stat)} +${amount}`],
    [/^\+([\d.]+[A-Za-z]*%) (.+) Concept$/, (_text, amount, currency) => `${t(currency)} 착상 +${amount}`],
    [/^([+-][\d.]+%) (.+) rarity chance$/, (_text, amount, rarity) => `${t(rarity)} 등장률 ${amount}`],
    [/^([+-][\d.]+%) (.+) chance$/, (_text, amount, rarity) => `${t(rarity)} 확률 ${amount}`],
    [/^\+([\d.]+) Max (.+) Sketch$/, (_text, amount, rarity) => `최대 ${t(rarity)} 스케치 +${amount}`],
    [/^\+([\d.]+) Guaranteed (.+) Sketch$/, (_text, amount, rarity) => `확정 ${t(rarity)} 스케치 +${amount}`],
    [/^Unscrambled (.+) sketches can be Guaranteed for (.+) slots$/, (_text, rarity, slots) => `해독된 ${t(rarity)} 스케치는 슬롯 ${slots}개로 확정할 수 있습니다.`],
    [/^([+-][\d.]+%) (.+) cost$/, (_text, amount, currency) => `${t(currency)} 비용 ${amount}`],
    [/^([+-][\d.]+%) (.+) cost (.+) cost reduction\. Applies to both Tools and Stat Upgrades\.$/, (_text, amount, titleCurrency, bodyCurrency) => `${t(titleCurrency)} 비용 ${amount}\n${t(bodyCurrency)} 비용 감소. 도구와 능력치 업그레이드 모두에 적용됩니다.`],
    [/^([+-][\d.]+%) (.+) cost (.+) 비용 감소\. 도구와 능력치 업그레이드 모두에 적용됩니다\.$/, (_text, amount, titleCurrency, bodyCurrency) => `${t(titleCurrency)} 비용 ${amount}\n${t(bodyCurrency)} 비용 감소. 도구와 능력치 업그레이드 모두에 적용됩니다.`],
    [/^\+([\d.]+%) (.+) rewards$/, (_text, amount, currency) => `${t(currency)} 보상 +${amount}`],
    [/^스케치 격파로 얻는 \+([\d.]+%) (.+) rewards (.+) 보상 배율\.$/, (_text, amount, titleCurrency, bodyCurrency) => `${t(titleCurrency)} 보상 +${amount}\n스케치 격파로 얻는 ${t(bodyCurrency)} 보상 배율.`],
    [/^\+([\d.]+) (.+) rewards exp\.$/, (_text, amount, currency) => `${t(currency)} 보상 지수 +${amount}`],
    [/^(.+) Bonus (.+) percentage\. \+([\d.]+%)$/, (_text, titleStat, bodyStat, amount) => `${t(titleStat)} 보너스\n${t(bodyStat)} 비율. +${amount}`],
    [/^(.+) rarity chance Chance for (.+) rarity sketches to appear on Redraw\. \(Highly Recommended for Masterpiece Archive progression\) \+([\d.]+%)$/, (_text, titleRarity, bodyRarity, amount) => `${t(titleRarity)} 등장률\n다시 그리기에서 ${t(bodyRarity)} 등급 스케치가 등장할 확률입니다. 걸작 아카이브 진행에 강력히 권장됩니다. +${amount}`],
    [/^Guaranteed (.+) Sketch Sets the maximum capacity of specific (.+) sketches you can explicitly guarantee in the Glossary\. \+([\d.]+)$/, (_text, titleRarity, bodyRarity, amount) => `확정 ${t(titleRarity)} 스케치\n용어집에서 직접 확정할 수 있는 특정 ${t(bodyRarity)} 스케치 슬롯 한도를 늘립니다. +${amount}`],
    [/^초안 풍요 Guaranteed Rough Sketch Sets the maximum capacity of specific Rough sketches you can explicitly guarantee in the Glossary\. \+([\d.]+)$/, (_text, amount) => `초안 풍요\n용어집에서 직접 확정할 수 있는 특정 초안 스케치 슬롯 한도를 늘립니다. +${amount}`],
    [/^Time Acceleration Global speed multiplier affecting everything including battle speed, currency generation, and conceptual synthesis\. Also works with offline gains\. \+([\d.]+)$/, (_text, amount) => `시간 가속\n전투 속도, 재화 생성, 착상 합성까지 모든 흐름을 빠르게 합니다. 오프라인 획득에도 적용됩니다. +${amount}`],
    [/^Temporal Flow Time Acceleration Global speed multiplier affecting everything including battle speed, currency generation, and conceptual synthesis\. Also works with offline gains\. \+([\d.]+)$/, (_text, amount) => `시간 흐름\n시간 가속\n전투 속도, 재화 생성, 착상 합성까지 모든 흐름을 빠르게 합니다. 오프라인 획득에도 적용됩니다. +${amount}`],
    [/^시간 흐름 Time Acceleration Global speed multiplier affecting everything including battle speed, currency generation, and conceptual synthesis\. Also works with offline gains\. \+([\d.]+)$/, (_text, amount) => `시간 흐름\n시간 가속\n전투 속도, 재화 생성, 착상 합성까지 모든 흐름을 빠르게 합니다. 오프라인 획득에도 적용됩니다. +${amount}`],
    [/^([+-][\d.]+s) death penalty Wait time after defeat\.$/, (_text, amount) => `부활 대기 ${amount.replace("s", "초")}\n패배 후 대기 시간.`],
    [/^(Swift Recovery|신속 회복) ([+-][\d.]+s) death penalty Wait time after defeat\.$/, (_text, title, amount) => `${t(title)}\n부활 대기 ${amount.replace("s", "초")}\n패배 후 대기 시간.`],
    [/^Overkill % of excess damage used to calculate how many extra victories are granted\. \+([\d.]+%)$/, (_text, amount) => `오버킬\n초과 피해 중 추가 승리 계산에 반영되는 비율입니다. +${amount}`],
    [/^(Divine Retribution|신성한 응징) Overkill % of excess damage used to calculate how many extra victories are granted\. \+([\d.]+%)$/, (_text, title, amount) => `${t(title)}\n오버킬\n초과 피해 중 추가 승리 계산에 반영되는 비율입니다. +${amount}`],
    [/^([+-][\d.]+%) Attack Delay$/, (_text, amount) => `공격 지연 ${amount}`],
    [/^([+-][\d.]+%) Attack Delay Attack delay reduction\.$/, (_text, amount) => `공격 지연 ${amount}\n공격 지연 감소.`],
    [/^([+-][\d.]+%) Attack Delay 공격 지연 감소\.$/, (_text, amount) => `공격 지연 ${amount}\n공격 지연 감소.`],
    [/^([+-][\d.]+s) flee penalty Wait time after fleeing\.$/, (_text, amount) => `도망 패널티 ${amount.replace("s", "초")}\n도망 후 대기 시간.`],
    [/^도망 패널티 ([+-][\d.]+초) Wait time after fleeing\.$/, (_text, amount) => `도망 패널티 ${amount}\n도망 후 대기 시간.`],
    [/^([+-][\d.]+) Decay Factor Controls how fast rewards decay per victory\. Reward after n kills = base \/ \(1 \+ n × decay\)\. Lower values mean slower decay and more total rewards\.$/, (_text, amount) => `보상 감소율 ${amount}\n승리당 보상이 얼마나 빠르게 줄어드는지 정합니다. n회 처치 후 보상 = 기본값 / (1 + n × 감소). 값이 낮을수록 보상이 천천히 줄어 총 보상이 많아집니다.`],
    [/^보상 감소율 ([+-][\d.]+) 승리당 보상이 얼마나 빠르게 줄어드는지 정합니다\. n회 처치 후 보상 = 기본값 \/ \(1 \+ n × 감소\)\. 값이 낮을수록 보상이 천천히 줄어 총 보상이 많아집니다\.$/, (_text, amount) => `보상 감소율 ${amount}\n승리당 보상이 얼마나 빠르게 줄어드는지 정합니다. n회 처치 후 보상 = 기본값 / (1 + n × 감소). 값이 낮을수록 보상이 천천히 줄어 총 보상이 많아집니다.`],
    [/^Automated Workflow Preserve active protocol state Tools auto-enabled on redraw, starting from top of active protocols list\.$/, "자동화 워크플로\n활성 프로토콜 상태를 유지합니다\n\n다시 그리기 시 활성 프로토콜 목록 위쪽부터 도구가 자동 활성화됩니다."],
    [/^자동화 워크플로 Preserve active protocol state Tools auto-enabled on redraw, starting from top of active protocols list\.$/, "자동화 워크플로\n활성 프로토콜 상태를 유지합니다\n\n다시 그리기 시 활성 프로토콜 목록 위쪽부터 도구가 자동 활성화됩니다."],
    [/^Preserve active protocol state Tools auto-enabled on redraw, starting from top of active protocols list\.$/, "활성 프로토콜 상태를 유지합니다\n\n다시 그리기 시 활성 프로토콜 목록 위쪽부터 도구가 자동 활성화됩니다."],
    [/^Start with free tools Tools unlocked on redraw, starting from top of tools list\.$/, "무료 도구를 가지고 시작합니다\n다시 그리기 시 도구 목록 위쪽부터 해금되는 도구."],
    [/^Start with free tools 다시 그리기 시 도구 목록 위쪽부터 해금되는 도구\.$/, "무료 도구를 가지고 시작합니다\n다시 그리기 시 도구 목록 위쪽부터 해금되는 도구."],
    [/^Unlock Buy Max for Skill Tree Unlocks the ["“]Max["”] button on all skill tree nodes\.?$/, "스킬 트리 최대 구매 해금\n모든 스킬 트리 노드의 \"최대\" 버튼을 해금합니다."],
    [/^스킬 트리 최대 구매 해금 Unlocks the ["“]Max["”] button on all skill tree nodes\.?$/, "스킬 트리 최대 구매 해금\n모든 스킬 트리 노드의 \"최대\" 버튼을 해금합니다."],
    [/^\+([\d.]+) Inspiration Stack Cap$/, (_text, amount) => `영감 중첩 상한 +${amount}`],
    [/^\+([\d.]+%) Quintessence gain$/, (_text, amount) => `정수 획득량 +${amount}`],
    [/^Quintessence gain Bonus Quintessence production for (.+) Concept in Conceptual Synthesizer\. \+([\d.]+%)$/, (_text, currency, amount) => `정수 획득량\n착상 합성기의 ${t(currency)} 착상 정수 생산 보너스. +${amount}`],
    [/^([\d.]+%) divider$/, (_text, amount) => `${amount} 속도 보정`],
    [/^([\d.]+%) multiplier$/, (_text, amount) => `${amount} 배율`],
    [/^First Ever Softcap in: (.+)$/, (_text, duration) => `첫 소프트캡까지: ${duration}`],
    [/^Requires (\d+) (.+) sketch(?:es)? in Glossary$/, (_text, count, rarity) => `용어집에 ${t(rarity)} 스케치 ${count}개 필요`],
    [/^REQUIRES (.+) PENDING QUINTESSENCE$/, (_text, count) => `대기 중인 정수 ${count} 필요`],
    [/^REQUIRES (\d+) ([A-Z]+) SKETCH(?:ES)? IN GLOSSARY$/, (_text, count, rarity) => `용어집에 ${t(rarity[0] + rarity.slice(1).toLowerCase())} 스케치 ${count}개 필요`],
    [/^REQUIRES (\d+) ([A-Z]+) SKETCH(?:ES)? IN GLOSSARY Current: (.+)$/, (_text, count, rarity, current) => `용어집에 ${t(rarity[0] + rarity.slice(1).toLowerCase())} 스케치 ${count}개 필요\n현재: ${current}`],
    [/^REQUIRES (\d+) ([A-Z]+) SKETCH(?:ES)? IN$/, (_text, count, rarity) => `필요: ${t(rarity[0] + rarity.slice(1).toLowerCase())} 스케치 ${count}개`],
    [/^GLOSSARY$/, "용어집"],
    [/^Current: ([+-]?[\d.]+)s$/, "현재: $1초"],
    [/^Current: (.+)$/, "현재: $1"],
    [/^현재: ([+-]?[\d.]+)s$/, "현재: $1초"],
    [/^\+([\d.]+) Max Victories$/, (_text, amount) => `최대 승리 +${amount}`],
    [/^\+([\d.]+) Time Acceleration$/, (_text, amount) => `시간 가속 +${amount}`],
    [/^\+([\d.]+)min max speedup time$/, (_text, amount) => `최대 가속 시간 +${amount}분`],
    [/^Reduces the cost of all (.+) stat upgrades by (.+)\.$/, (_text, currency, amount) => `모든 ${t(currency)} 능력치 업그레이드 비용을 ${amount} 줄입니다.`],
    [/^Automatically produces Reward ([\d.]+%) of (.+) you have gotten from Battle per second\.$/, (_text, amount, currency) => `전투로 얻은 ${t(currency)}의 ${amount}를 초당 자동 생산합니다.`],
    [/^Automatically produces ([\d.]+%) of (.+) you have gotten from Battle per second\.$/, (_text, amount, currency) => `전투로 얻은 ${t(currency)}의 ${amount}를 초당 자동 생산합니다.`],
    [/^초당 보상 ([\d.]+%) of (.+) you have gotten from Battle을 자동 생산합니다\.$/, (_text, amount, currency) => `전투로 얻은 ${t(currency)}의 ${amount}를 초당 자동 생산합니다.`],
    [/^Automatically produces (.+) (.+) per second\.$/, (_text, amount, currency) => `초당 ${t(currency)} ${amount}을 자동 생산합니다.`],
    [/^Grants \+(.+) Extra Victories per win\. Stacks with Overkill bonus\.$/, (_text, count) => `승리마다 추가 승리 +${count}회를 부여합니다. 오버킬 보너스와 중첩됩니다.`],
    [/^When defeating an enemy, (.+)% chance to lose (.+)% of buffs and (.+)% of debuffs\.$/, (_text, chance, buffLoss, debuffLoss) => `적을 격파할 때 ${chance}% 확률로 버프 ${buffLoss}%와 디버프 ${debuffLoss}%를 잃습니다.`],
  ], "tooltips");
})(typeof globalThis !== "undefined" ? globalThis : window);
