(function initRejectedDraftPatterns(globalScope) {
  const glossary = globalScope.REJECTED_DRAFT_KO_GLOSSARY || {};
  const t = (value) => glossary[value] || globalScope.REJECTED_DRAFT_KO_TRANSLATIONS?.[value] || value;
  const scrollingTipTranslations = globalScope.REJECTED_DRAFT_KO_SCROLLING_TIP_TRANSLATIONS || {};
  const scrollingTipLabels = globalScope.REJECTED_DRAFT_KO_SCROLLING_TIP_LABELS || {};
  const escapeRegExp = (value) => String(value).replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  const scrollingTipBodies = Object.keys(scrollingTipTranslations).map(escapeRegExp);
  const scrollingTipPattern = scrollingTipBodies.length
    ? new RegExp(`^(TIP|팁|CRITIQUE|비평|FACT|사실|JOKE|농담|LPT|생활 팁) (#.+): (${scrollingTipBodies.join("|")})$`)
    : /^$/;

  globalScope.REJECTED_DRAFT_KO_PATTERNS = [
    [/^Gallery Tutorial: (.+)$/, "갤러리 튜토리얼: $1"],
    [/^Shop Tutorial: (.+)$/, "상점 튜토리얼: $1"],
    [/^Archive Tutorial: (.+)$/, "아카이브 튜토리얼: $1"],
    [/^Battle Tutorial: (.+)$/, "전투 튜토리얼: $1"],
    [/^(\d+) Victory$/, "$1승"],
    [/^(\d+) Victories$/, "$1승"],
    [/^(.+) defeated!$/, (_text, name) => `${t(name)} 격파!`],
    [/^Defeated by (.+)! (.+) second cooldown\.$/, (_text, name, cooldown) => `${t(name)}에게 패배했습니다! ${cooldown}초 쿨다운.`],
    [/^\+(.+) Victories$/, (_text, count) => `승리 +${count}`],
    [/^\+(.+) Victories \((.+)\)$/, (_text, count, kind) => `승리 +${count} (${t(kind)})`],
    [/^Encountered: (.+)$/, (_text, name) => `조우: ${t(name)}`],
    [/^Unscrambled: (.+)$/, (_text, name) => `해독됨: ${t(name)}`],
    [/^New version unlocked: (.+)!$/, (_text, name) => `새 버전 해금: ${t(name)}!`],
    [/^New Glossary Entry: (.+) Glossary Multiplier \+(.+) \(New: (.+)x\)$/, (_text, name, amount, value) => `새 용어집 항목: ${t(name)}\n용어집 배율 +${amount} (새 값: ${value}배)`],
    [/^New Glossary Entry: (.+)$/, (_text, name) => `새 용어집 항목: ${t(name)}`],
    [/^Glossary Multiplier \+(.+) \(New: (.+)x\)$/, (_text, amount, value) => `용어집 배율 +${amount} (새 값: ${value}배)`],
    [/^Feat Medal Purchased! Feat Mult \+(.+) \(Now: (.+)x\)$/, (_text, amount, value) => `업적 메달 구매 완료!\n업적 배율 +${amount} (현재: ${value}배)`],
    [/^Feat Medal Purchased!$/, "업적 메달 구매 완료!"],
    [/^Feat Mult \+(.+) \(Now: (.+)x\)$/, (_text, amount, value) => `업적 배율 +${amount} (현재: ${value}배)`],
    [/^Feat Achieved: (.+)!$/, (_text, name) => `업적 달성: ${t(name)}!`],
    [/^(.+) is affordable!$/, (_text, name) => `${t(name)} 구매 가능!`],
    [/^(TIP|팁) (#.+): Top right icon on each sketch on Gallery page can hide sketches that are of no use to you\.$/, (_text, _label, id) => `팁 ${id}: 갤러리 페이지에서 각 스케치 오른쪽 위 아이콘을 누르면 쓸모없는 스케치를 숨길 수 있습니다.`],
    [/^(TIP|팁) (#.+): You can review the Tutorial anytime in Settings\.$/, (_text, _label, id) => `팁 ${id}: 튜토리얼은 설정에서 언제든 다시 볼 수 있습니다.`],
    [/^(CRITIQUE|비평) (#.+): I hope you're not playing this at work\. Or do\. I'm not HR\.$/, (_text, _label, id) => `비평 ${id}: 직장에서 이 게임을 하고 있지 않길 바랍니다. 뭐, 해도 됩니다. 저는 HR이 아니니까요.`],
    [/^(JOKE|농담) (#.+): The painter was hospitalized\. Doctors say he had too many strokes\.$/, (_text, _label, id) => `농담 ${id}: 화가가 입원했습니다. 의사 말로는 붓질이 너무 많았다네요.`],
    [/^(JOKE|농담) (#.+): Shout out to people who don't know what the opposite of 'in' is\.$/, (_text, _label, id) => `농담 ${id}: 'in'의 반대말을 모르는 분들께 한마디. out!`],
    [/^(FACT|사실) (#.+): The average person spends 6 months of their life waiting for red lights to turn green\.$/, (_text, _label, id) => `사실 ${id}: 평균적인 사람은 평생 6개월을 빨간불이 초록불로 바뀌길 기다리며 보냅니다.`],
    [/^(FACT|사실) (#.+): John Steinbeck used up to 60 pencils a day\. He would have loved auto-battle\.$/, (_text, _label, id) => `사실 ${id}: John Steinbeck은 하루에 연필을 최대 60자루까지 썼습니다. 자동 전투를 꽤 좋아했을 겁니다.`],
    [/^(FACT|사실) (#.+): Archaeologists have found edible honey in ancient Egyptian tombs\. It never spoils\.$/, (_text, _label, id) => `사실 ${id}: 고고학자들은 고대 이집트 무덤에서 아직 먹을 수 있는 꿀을 발견했습니다. 꿀은 상하지 않습니다.`],
    [/^(LPT|생활 팁) (#.+): Fix your posture\. Your future back will thank you\.$/, (_text, _label, id) => `생활 팁 ${id}: 자세를 바로잡으세요. 미래의 허리가 고마워할 겁니다.`],
    [/^(TIP|팁) (#.+): After unlocking Portfolio Review tool, it may be worthwhile to unhide all sketches and squeeze them for more\.$/, (_text, _label, id) => `팁 ${id}: 스케치 순회 도구를 해금했다면 숨겨 둔 스케치를 모두 다시 표시해서 보상을 더 챙겨 볼 만합니다.`],
    [/^(TIP|팁) (#.+): The "locks" at top of sidebars make them retractable\.$/, (_text, _label, id) => `팁 ${id}: 사이드바 상단의 "잠금"을 누르면 접어 둘 수 있습니다.`],
    [/^(TIP|팁) (#.+): Fleeing isn't just for escaping; use it to quickly rotate through sketches searching for specific rewards\.$/, (_text, _label, id) => `팁 ${id}: 도망은 탈출용만이 아닙니다. 원하는 보상을 찾을 때 스케치를 빠르게 돌려 보는 데도 쓰세요.`],
    [/^(TIP|팁) (#.+): Statuses like Poison are effective against tanky sketches\.$/, (_text, _label, id) => `팁 ${id}: ${t("Poison")} 같은 상태 효과는 튼튼한 스케치에게 효과적입니다.`],
    [/^(LPT|생활 팁) (#.+): Floss your teeth\. You only need to floss the ones you want to keep\.$/, (_text, _label, id) => `생활 팁 ${id}: 치실을 쓰세요. 계속 쓰고 싶은 치아에만 쓰면 됩니다.`],
    [/^(FACT|사실) (#.+): The Eiffel Tower can be 15 cm taller during the summer due to thermal expansion\.$/, (_text, _label, id) => `사실 ${id}: 에펠탑은 열팽창 때문에 여름에 최대 15cm 더 높아질 수 있습니다.`],
    [/^(CRITIQUE|비평) (#.+): A redraw is just a fancy word for professional procrastination\.$/, (_text, _label, id) => `비평 ${id}: 다시 그리기는 전문적인 미루기를 그럴듯하게 부르는 말일 뿐입니다.`],
    [/^(LPT|생활 팁) (#.+): Rotate your wrists\. Draw the alphabet with your nose to relax your neck\.$/, (_text, _label, id) => `생활 팁 ${id}: 손목을 돌려 주세요. 목을 풀려면 코로 알파벳을 그려 보세요.`],
    [/^(LPT|생활 팁) (#.+): Stretch your wrists\. Carpal tunnel is the real end-game boss\.$/, (_text, _label, id) => `생활 팁 ${id}: 손목을 스트레칭하세요. 손목터널증후군이 진짜 엔드게임 보스입니다.`],
    [/^(FACT|사실) (#.+): The first pencils were made of solid graphite wrapped in sheepskin\.$/, (_text, _label, id) => `사실 ${id}: 최초의 연필은 양가죽으로 감싼 고체 흑연으로 만들어졌습니다.`],
    [/^(JOKE|농담) (#.+): I tried to paint the sky, but I blue it\.$/, (_text, _label, id) => `농담 ${id}: 하늘을 칠하려 했는데, 파랗게 질려 버렸습니다.`],
    [/^(TIP|팁) (#.+): There are other flavors for this text \(see settings\): Snarky Comments \(Critiques\), Life Pro Tips \(LPT\), Jokes, and Facts\.$/, (_text, _label, id) => `팁 ${id}: 이 문구에는 다른 종류도 있습니다(설정에서 확인): 빈정거리는 코멘트(비평), 생활 팁(LPT), 농담, 사실.`],
    [scrollingTipPattern, (_text, label, id, body) => `${scrollingTipLabels[label] || label} ${id}: ${scrollingTipTranslations[body]}`],
    [/^TIP (#.+)$/, "팁 $1"],
    [/^FACT (#.+)$/, "사실 $1"],
    [/^CRITIQUE (#.+)$/, "비평 $1"],
    [/^JOKE (#.+)$/, "농담 $1"],
    [/^LPT (#.+)$/, "생활 팁 $1"],
    [/^Chance to apply (.+)\.$/, (_text, effect) => `${t(effect)} 적용 확률.`],
    [/^Chance to apply (.+) to enemy\.$/, (_text, effect) => `적에게 ${t(effect)} 적용 확률.`],
    [/^Chance to gain (.+) stacks on attack\.$/, (_text, effect) => `공격 시 ${t(effect)} 중첩 획득 확률.`],
    [/^Chance to gain (.+) on attack\.$/, (_text, effect) => `공격 시 ${t(effect)} 획득 확률.`],
    [/^\+([\d.]+%) (.+) per level$/, (_text, amount, stat) => `레벨당 ${t(stat)} +${amount}`],
    [/^\+([\d.]+) (.+) per level$/, (_text, amount, stat) => `레벨당 ${t(stat)} +${amount}`],
    [/^\+([\d.]+[A-Za-z]*%) (.+) Concept$/, (_text, amount, currency) => `${t(currency)} 착상 +${amount}`],
    [/^([+-][\d.]+%) (.+) rarity chance$/, (_text, amount, rarity) => `${t(rarity)} 등장률 ${amount}`],
    [/^([+-][\d.]+%) (.+) chance$/, (_text, amount, rarity) => `${t(rarity)} 확률 ${amount}`],
    [/^\+([\d.]+) Max (.+) Sketch$/, (_text, amount, rarity) => `최대 ${t(rarity)} 스케치 +${amount}`],
    [/^\+([\d.]+) Guaranteed (.+) Sketch$/, (_text, amount, rarity) => `확정 ${t(rarity)} 스케치 +${amount}`],
    [/^Unscrambled (.+) sketches can be Guaranteed for (.+) slots$/, (_text, rarity, slots) => `해독된 ${t(rarity)} 스케치는 슬롯 ${slots}개로 확정할 수 있습니다.`],
    [/^([+-][\d.]+%) (.+) cost$/, (_text, amount, currency) => `${t(currency)} 비용 ${amount}`],
    [/^([+-][\d.]+%) (.+) cost (.+) cost reduction\. Applies to both Tools and Stat Upgrades\.$/, (_text, amount, titleCurrency, bodyCurrency) => `${t(titleCurrency)} 비용 ${amount}\n${t(bodyCurrency)} 비용 감소. 도구와 능력치 업그레이드 모두에 적용됩니다.`],
    [/^([+-][\d.]+%) (.+) cost (.+) 비용 감소\. 도구와 능력치 업그레이드 모두에 적용됩니다\.$/, (_text, amount, titleCurrency, bodyCurrency) => `${t(titleCurrency)} 비용 ${amount}\n${t(bodyCurrency)} 비용 감소. 도구와 능력치 업그레이드 모두에 적용됩니다.`],
    [/^\+([\d.]+%) (.+) rewards$/, (_text, amount, currency) => `${t(currency)} 보상 +${amount}`],
    [/^스케치 격파로 얻는 \+([\d.]+%) (.+) rewards (.+) 보상 배율\.$/, (_text, amount, titleCurrency, bodyCurrency) => `${t(titleCurrency)} 보상 +${amount}\n스케치 격파로 얻는 ${t(bodyCurrency)} 보상 배율.`],
    [/^\+([\d.]+) (.+) rewards exp\.$/, (_text, amount, currency) => `${t(currency)} 보상 지수 +${amount}`],
    [/^(.+) Bonus (.+) percentage\. \+([\d.]+%)$/, (_text, titleStat, bodyStat, amount) => `${t(titleStat)} 보너스\n${t(bodyStat)} 비율. +${amount}`],
    [/^(.+) rarity chance Chance for (.+) rarity sketches to appear on Redraw\. \(Highly Recommended for Masterpiece Archive progression\) \+([\d.]+%)$/, (_text, titleRarity, bodyRarity, amount) => `${t(titleRarity)} 등장률\n다시 그리기에서 ${t(bodyRarity)} 등급 스케치가 등장할 확률입니다. 걸작 아카이브 진행에 강력히 권장됩니다. +${amount}`],
    [/^Guaranteed (.+) Sketch Sets the maximum capacity of specific (.+) sketches you can explicitly guarantee in the Glossary\. \+([\d.]+)$/, (_text, titleRarity, bodyRarity, amount) => `확정 ${t(titleRarity)} 스케치\n용어집에서 직접 확정할 수 있는 특정 ${t(bodyRarity)} 스케치 슬롯 한도를 늘립니다. +${amount}`],
    [/^초안 풍요 Guaranteed Rough Sketch Sets the maximum capacity of specific Rough sketches you can explicitly guarantee in the Glossary\. \+([\d.]+)$/, (_text, amount) => `초안 풍요\n용어집에서 직접 확정할 수 있는 특정 초안 스케치 슬롯 한도를 늘립니다. +${amount}`],
    [/^Temporal Flow Time Acceleration Global speed multiplier affecting everything including battle speed, currency generation, and conceptual synthesis\. Also works with offline gains\. \+([\d.]+)$/, (_text, amount) => `시간 흐름\n시간 가속\n전투 속도, 재화 생성, 착상 합성까지 모든 흐름을 빠르게 합니다. 오프라인 획득에도 적용됩니다. +${amount}`],
    [/^시간 흐름 Time Acceleration Global speed multiplier affecting everything including battle speed, currency generation, and conceptual synthesis\. Also works with offline gains\. \+([\d.]+)$/, (_text, amount) => `시간 흐름\n시간 가속\n전투 속도, 재화 생성, 착상 합성까지 모든 흐름을 빠르게 합니다. 오프라인 획득에도 적용됩니다. +${amount}`],
    [/^([+-][\d.]+%) Attack Delay$/, (_text, amount) => `공격 지연 ${amount}`],
    [/^([+-][\d.]+%) Attack Delay Attack delay reduction\.$/, (_text, amount) => `공격 지연 ${amount}\n공격 지연 감소.`],
    [/^([+-][\d.]+%) Attack Delay 공격 지연 감소\.$/, (_text, amount) => `공격 지연 ${amount}\n공격 지연 감소.`],
    [/^([+-][\d.]+s) flee penalty Wait time after fleeing\.$/, (_text, amount) => `도망 패널티 ${amount.replace("s", "초")}\n도망 후 대기 시간.`],
    [/^도망 패널티 ([+-][\d.]+초) Wait time after fleeing\.$/, (_text, amount) => `도망 패널티 ${amount}\n도망 후 대기 시간.`],
    [/^([+-][\d.]+) Decay Factor Controls how fast rewards decay per victory\. Reward after n kills = base \/ \(1 \+ n × decay\)\. Lower values mean slower decay and more total rewards\.$/, (_text, amount) => `보상 감소율 ${amount}\n승리당 보상이 얼마나 빠르게 줄어드는지 정합니다. n회 처치 후 보상 = 기본값 / (1 + n × 감소). 값이 낮을수록 보상이 천천히 줄어 총 보상이 많아집니다.`],
    [/^Automated Workflow Preserve active protocol state Tools auto-enabled on redraw, starting from top of active protocols list\.$/, "자동화 워크플로\n활성 프로토콜 상태를 유지합니다\n\n다시 그리기 시 활성 프로토콜 목록 위쪽부터 도구가 자동 활성화됩니다."],
    [/^자동화 워크플로 Preserve active protocol state Tools auto-enabled on redraw, starting from top of active protocols list\.$/, "자동화 워크플로\n활성 프로토콜 상태를 유지합니다\n\n다시 그리기 시 활성 프로토콜 목록 위쪽부터 도구가 자동 활성화됩니다."],
    [/^Preserve active protocol state Tools auto-enabled on redraw, starting from top of active protocols list\.$/, "활성 프로토콜 상태를 유지합니다\n\n다시 그리기 시 활성 프로토콜 목록 위쪽부터 도구가 자동 활성화됩니다."],
    [/^Start with free tools Tools unlocked on redraw, starting from top of tools list\.$/, "무료 도구를 가지고 시작합니다\n다시 그리기 시 도구 목록 위쪽부터 해금되는 도구."],
    [/^Start with free tools 다시 그리기 시 도구 목록 위쪽부터 해금되는 도구\.$/, "무료 도구를 가지고 시작합니다\n다시 그리기 시 도구 목록 위쪽부터 해금되는 도구."],
    [/^Unlock Buy Max for Skill Tree Unlocks the ["“]Max["”] button on all skill tree nodes\.?$/, "스킬 트리 최대 구매 해금\n모든 스킬 트리 노드의 \"최대\" 버튼을 해금합니다."],
    [/^스킬 트리 최대 구매 해금 Unlocks the ["“]Max["”] button on all skill tree nodes\.?$/, "스킬 트리 최대 구매 해금\n모든 스킬 트리 노드의 \"최대\" 버튼을 해금합니다."],
    [/^\+([\d.]+) Inspiration Stack Cap$/, (_text, amount) => `영감 중첩 상한 +${amount}`],
    [/^\+([\d.]+%) Quintessence gain$/, (_text, amount) => `정수 획득량 +${amount}`],
    [/^Quintessence gain Bonus Quintessence production for (.+) Concept in Conceptual Synthesizer\. \+([\d.]+%)$/, (_text, currency, amount) => `정수 획득량\n착상 합성기의 ${t(currency)} 착상 정수 생산 보너스. +${amount}`],
    [/^([\d.]+%) divider$/, (_text, amount) => `${amount} 속도 보정`],
    [/^([\d.]+%) multiplier$/, (_text, amount) => `${amount} 배율`],
    [/^First Ever Softcap in: (.+)$/, (_text, duration) => `첫 소프트캡까지: ${duration}`],
    [/^Requires (\d+) (.+) sketch(?:es)? in Glossary$/, (_text, count, rarity) => `용어집에 ${t(rarity)} 스케치 ${count}개 필요`],
    [/^REQUIRES (.+) PENDING QUINTESSENCE$/, (_text, count) => `대기 중인 정수 ${count} 필요`],
    [/^REQUIRES (\d+) ([A-Z]+) SKETCH(?:ES)? IN GLOSSARY$/, (_text, count, rarity) => `용어집에 ${t(rarity[0] + rarity.slice(1).toLowerCase())} 스케치 ${count}개 필요`],
    [/^REQUIRES (\d+) ([A-Z]+) SKETCH(?:ES)? IN GLOSSARY Current: (.+)$/, (_text, count, rarity, current) => `용어집에 ${t(rarity[0] + rarity.slice(1).toLowerCase())} 스케치 ${count}개 필요\n현재: ${current}`],
    [/^REQUIRES (\d+) ([A-Z]+) SKETCH(?:ES)? IN$/, (_text, count, rarity) => `필요: ${t(rarity[0] + rarity.slice(1).toLowerCase())} 스케치 ${count}개`],
    [/^GLOSSARY$/, "용어집"],
    [/^Current: (.+)$/, "현재: $1"],
    [/^\+([\d.]+) Max Victories$/, (_text, amount) => `최대 승리 +${amount}`],
    [/^\+([\d.]+) Time Acceleration$/, (_text, amount) => `시간 가속 +${amount}`],
    [/^\+([\d.]+)min max speedup time$/, (_text, amount) => `최대 가속 시간 +${amount}분`],
    [/^Reduces the cost of all (.+) stat upgrades by (.+)\.$/, (_text, currency, amount) => `모든 ${t(currency)} 능력치 업그레이드 비용을 ${amount} 줄입니다.`],
    [/^Automatically produces Reward ([\d.]+%) of (.+) you have gotten from Battle per second\.$/, (_text, amount, currency) => `전투로 얻은 ${t(currency)}의 ${amount}를 초당 자동 생산합니다.`],
    [/^Automatically produces ([\d.]+%) of (.+) you have gotten from Battle per second\.$/, (_text, amount, currency) => `전투로 얻은 ${t(currency)}의 ${amount}를 초당 자동 생산합니다.`],
    [/^Automatically produces (.+) (.+) per second\.$/, (_text, amount, currency) => `초당 ${t(currency)} ${amount}을 자동 생산합니다.`],
    [/^(.+) victories boost (.+) Concept$/, (_text, rarity, currency) => `${t(rarity)} 승리가 ${t(currency)} 착상을 강화합니다.`],
    [/^(\d+)x (.+) generator$/, (_text, amount, currency) => `${t(currency)} 생성기 ${amount}배`],
    [/^(.+) Generator$/, (_text, currency) => `${t(currency)} 생성기`],
    [/^(.+) Discount$/, (_text, currency) => `${t(currency)} 할인`],
    [/^(.+) Refinement$/, (_text, currency) => `${t(currency)} 정제`],
    [/^Bonus (.+) percentage\.$/, (_text, stat) => `추가 ${t(stat)} 비율.`],
    [/^(.+) Increase$/, (_text, stat) => `${t(stat)} 증가`],
    [/^(.+) Concept$/, (_text, currency) => `${t(currency)} 착상`],
    [/^(.+) Overclock$/, (_text, currency) => `${t(currency)} 오버클럭`],
    [/^(.+) Exponent$/, (_text, currency) => `${t(currency)} 지수`],
    [/^(.+) Reward$/, (_text, currency) => `${t(currency)} 보상`],
    [/^(.+) Cost$/, (_text, currency) => `${t(currency)} 비용`],
    [/^(.+) Rarity$/, (_text, rarity) => `${t(rarity)} 희귀도`],
    [/^(.+) Expansion$/, (_text, rarity) => `${t(rarity)} 확장`],
    [/^Multiplier for passive (.+) generation\.$/, (_text, currency) => `패시브 ${t(currency)} 생성 배율.`],
    [/^(.+) reward multiplier from defeating sketches\.$/, (_text, currency) => `스케치 격파로 얻는 ${t(currency)} 보상 배율.`],
    [/^(.+) cost reduction\. Applies to both Tools and Stat Upgrades\.$/, (_text, currency) => `${t(currency)} 비용 감소. 도구와 능력치 업그레이드 모두에 적용됩니다.`],
    [/^Multiplier for (.+) Concept production in the Conceptual Synthesizer\.$/, (_text, currency) => `착상 합성기의 ${t(currency)} 착상 생산 배율.`],
    [/^Concepts are the physical manifestation of your artistic progress\. They are gained by reaching milestones with total earned (.+) throughout this run\.$/, (_text, currency) => `착상은 예술적 진행이 형태를 얻은 결과입니다. 이번 실행 동안 총 ${t(currency)} 획득량 마일스톤에 도달하면 얻습니다.`],
    [/^Milestones: 1 start production \| 2,3,4 = (.+)x \| 5,6,7 = (.+)x \| 8,9,10 = (.+)x \| 11 = (.+)x$/, (_text, m2, m5, m8, m11) => `마일스톤: 1 생산 시작 | 2,3,4 = ${m2}배 | 5,6,7 = ${m5}배 | 8,9,10 = ${m8}배 | 11 = ${m11}배`],
    [/^Multiplicatively increased by Feat Medal Base \(x(.+)\) per medal\. Multiplies all currency rewards\.$/i, (_text, value) => `메달을 하나 살 때마다 업적 메달 기준값(x${value})만큼 곱연산으로 증가합니다. 모든 재화 보상에 적용됩니다.`],
    [/^(.+) rewards exp\. Raises (.+) rewards to an exponential power\. Applies after (.+) Reward multiplier\. Formula: Reward \^ \(1 \+ \(Level\/100\)\) \+(.+)$/, (_text, titleCurrency, bodyCurrency, multiplierCurrency, bonus) => `${t(titleCurrency)} 보상 지수\n${t(bodyCurrency)} 보상에 지수 보정을 적용합니다. ${t(multiplierCurrency)} 보상 배율 이후 적용됩니다. 공식: 보상 ^ (1 + (레벨/100)) +${bonus}`],
    [/^Raises (.+) rewards to an exponential power\. Applies after (.+) Reward multiplier\. Formula: Reward \^ \(1 \+ \(Level\/100\)\)$/, (_text, currency) => `${t(currency)} 보상을 지수로 증가시킵니다. ${t(currency)} 보상 배율 이후 적용됩니다. 공식: 보상 ^ (1 + (레벨/100))`],
    [/^Chance for (.+) rarity sketches to appear on Redraw\.$/, (_text, rarity) => `다시 그리기에서 ${t(rarity)} 등급 스케치가 등장할 확률.`],
    [/^Sets the maximum capacity of specific (.+) sketches you can explicitly guarantee in the Glossary\.$/, (_text, rarity) => `용어집에서 명시적으로 확정할 수 있는 특정 ${t(rarity)} 스케치의 최대 수를 설정합니다.`],
    [/^Defeat every (.+) rarity sketch\.$/, (_text, rarity) => `모든 ${t(rarity)} 등급 스케치를 격파하세요.`],
    [/^Defeat every standard (.+) rarity sketch\.$/, (_text, rarity) => `모든 표준 ${t(rarity)} 등급 스케치를 격파하세요.`],
    [/^Defeat half of the (.+) rarity sketches\.$/, (_text, rarity) => `${t(rarity)} 등급 스케치의 절반을 격파하세요.`],
    [/^Defeat a quarter of the (.+) rarity sketches\.$/, (_text, rarity) => `${t(rarity)} 등급 스케치의 4분의 1을 격파하세요.`],
    [/^Reach (.+) Redraws across your journey\.$/, (_text, count) => `여정 전체에서 다시 그리기 ${count}회에 도달하세요.`],
    [/^Reach (.+) victories against (.+) sketches.*$/, (_text, count, rarity) => `${t(rarity)} 스케치를 상대로 ${count}승에 도달하세요.`],
    [/^Roll (.+) (.+) Sketches in a single Redraw\.$/, (_text, count, rarity) => `한 번의 다시 그리기에서 ${t(rarity)} 스케치 ${count}개를 뽑으세요.`],
    [/^Flee (.+) battles across all redraws\.$/, (_text, count) => `모든 다시 그리기에서 전투 ${count}회 도망치세요.`],
    [/^Reach (.+) or greater (.+) \((.+)\)\.$/, (_text, amount, stat, code) => `${t(stat)} (${code})을 ${amount} 이상 달성하세요.`],
    [/^Arrange (.+) contiguously in the Gallery\.$/, (_text, names) => `갤러리에서 ${names}를 연속으로 배치하세요.`],
    [/^Open the (.+) modal for (.+) different sketches\.$/, (_text, modal, count) => `서로 다른 스케치 ${count}개의 ${t(modal)} 모달을 여세요.`],
    [/^Click any (.+) artist credit link\.$/, (_text, artist) => `${artist} 아티스트 크레딧 링크를 아무거나 클릭하세요.`],
    [/^Fully defeat the (.+) Dummy\.$/, (_text, name) => `${t(name)} 더미를 완전히 격파하세요.`],
    [/^Lose (.+) battles across all redraws\.$/, (_text, count) => `모든 다시 그리기에서 전투 ${count}회 패배하세요.`],
    [/^Trigger the pre-battle (.+) (.+) times\.$/, (_text, action, count) => `전투 전 ${t(action)}을 ${count}회 발동하세요.`],
    [/^Unlock the fourth (.+) alternate version\.$/, (_text, name) => `${name}의 네 번째 대체 버전을 해금하세요.`],
    [/^Have all (.+) Active Protocols unlocked but disabled simultaneously\.$/, (_text, count) => `활성 프로토콜 ${count}개를 모두 해금했지만 동시에 비활성화하세요.`],
    [/^Earn (.+) extra victories from a single overkill hit\.$/, (_text, count) => `단일 오버킬 타격으로 추가 승리 ${count}회를 얻으세요.`],
    [/^Stack (.+) (.+) on yourself\.$/, (_text, count, effect) => `자신에게 ${t(effect)}을 ${count}개 중첩하세요.`],
    [/^Perform a Redraw with (.+) total victories\.$/, (_text, count) => `총 승리 ${count}회 상태로 다시 그리기를 수행하세요.`],
    [/^Reach (.+) victories in a single redraw with zero deaths\.$/, (_text, count) => `한 번의 다시 그리기에서 사망 없이 ${count}승에 도달하세요.`],
    [/^Use the (.+) (.+) times\.$/, (_text, tool, count) => `${t(tool)}를 ${count}회 사용하세요.`],
    [/^Use (.+) (.+) times\.$/, (_text, tool, count) => `${t(tool)}를 ${count}회 사용하세요.`],
    [/^Unlock (.+) Tools in a single redraw\.$/, (_text, count) => `한 번의 다시 그리기에서 도구 ${count}개를 해금하세요.`],
    [/^Have at least (.+) (.+) stacks on yourself at one time\.$/, (_text, count, effect) => `한 번에 자신에게 ${t(effect)} 중첩을 최소 ${count}개 보유하세요.`],
    [/^Apply a total of (.+) (.+) stacks\.$/, (_text, count, effect) => `${t(effect)} 중첩을 총 ${count}개 적용하세요.`],
    [/^Requires defeating (.+)$/, (_text, name) => `${t(name)} 격파 필요`],
    [/^Unlock required defeating (.+)$/, (_text, name) => `해금하려면 ${t(name)} 격파 필요`],
    [/^(.+) appeared in (.+) redraws$/, (_text, name, count) => `${t(name)} 등장 횟수: 다시 그리기 ${count}회`],
    [/^Total (.+) used this playthrough\.$/, (_text, name) => `이번 플레이에서 사용한 ${t(name)} 총량.`],
    [/^Filter by sketches rewarding (.+)\.$/, (_text, currency) => `${t(currency)}를 보상하는 스케치로 필터링합니다.`],
    [/^Produces (.+) Concept$/, (_text, currency) => `${t(currency)} 착상 생산`],
    [/^Player stack cap: (.+)$/, "플레이어 중첩 상한: $1"],
    [/^(.+) Visibility$/, (_text, rarity) => `${t(rarity)} 표시 여부`],
    [/^(.+) rarity sketches\.$/, (_text, rarity) => `${t(rarity)} 등급 스케치.`],
    [/^\+([\d.]+%) (.+)$/, (_text, amount, stat) => `${t(stat)} +${amount}`],
    [/^\+([\d.]+) (.+)$/, (_text, amount, stat) => `${t(stat)} +${amount}`]
  ];
})(typeof globalThis !== "undefined" ? globalThis : window);
