(function initRejectedDraftEnglishUiFallback(globalScope) {
  const registry = globalScope.RejectedDraftKoRegistry;
  registry.registerTranslations( {
    "A-Z": "가나다순",
    "All": "전체",
    "Angry accident.": "화난 사고뭉치.",
    "Anxiety with legs.": "다리 달린 불안감.",
    "Art is pain. Inflict it and reclaim your glory.": "예술은 고통이다. 고통을 주고 영광을 되찾아라.",
    "Battle": "전투",
    "Battle Stats": "전투 능력치",
    "Blinding. Honest. Every stroke exposed.": "눈부시고 정직하다. 모든 선이 드러난다.",
    "Challenge": "도전",
    "Click Challenge to enter battle.": "도전을 눌러 전투에 진입하세요.",
    "Combat runs in the background, allowing you to freely navigate to other tabs.": "전투는 백그라운드에서 진행되므로 다른 탭으로 자유롭게 이동할 수 있습니다.",
    "Continue": "계속",
    "Cool. Quiet. A refuge for the unfinished.": "차갑고 조용하다. 미완성들을 위한 피난처.",
    "Core": "핵심",
    "Current Specs": "현재 능력치",
    "Death Recovery": "부활 대기",
    "Decay Factor": "보상 감소율",
    "Default": "기본",
    "Defense": "방어",
    "Economy": "경제",
    "Enemy": "적",
    "English": "영어",
    "Euclid is crying.": "유클리드가 울고 있다.",
    "Each sketch grants specific Stat and Currency rewards upon victory!": "각 스케치는 승리 시 특정 능력치와 재화 보상을 줍니다!",
    "Every stroke exposed.": "모든 선이 드러난다.",
    "Finish": "완료",
    "Flee": "도망",
    "Flee Penalty": "도망 패널티",
    "Fundamentals": "기본 능력",
    "Gallery": "갤러리",
    "Glossary Multiplier": "용어집 배율",
    "Language (Non-English translations are incomplete. Help us translate! Join Discord for info)": "언어 (영어 외 번역은 아직 불완전합니다. 번역을 돕고 싶다면 Discord에 참여하세요)",
    "MND": "정신",
    "Minimize": "최소화",
    "MXD": "최대 피해",
    "NEW": "신규",
    "No active protocols available": "사용 가능한 활성 프로토콜이 없습니다",
    "No battle in progress": "진행 중인 전투 없음",
    "Offense": "공격",
    "Perspective Block": "원근감 블록",
    "Player": "플레이어",
    "Previous": "이전",
    "Pristine": "프리스틴",
    "Protocols": "프로토콜",
    "Rarity": "희귀도",
    "Rejected Draft": "Rejected Draft",
    "Reposition": "위치 조정",
    "Rewards": "보상",
    "Select Language": "언어 선택",
    "Select": "선택",
    "Select your preferred theme": "선호하는 테마를 선택하세요",
    "Skip": "건너뛰기",
    "Skip Tutorial": "튜토리얼 건너뛰기",
    "Smudge": "얼룩",
    "Sort": "정렬",
    "Stats": "능력치",
    "Stick Man": "졸라맨",
    "Shop": "상점",
    "The Challenge": "도전",
    "The Premise": "전제",
    "The Rejected Draft": "The Rejected Draft",
    "The Universe is a story being written by the Artist, but you are the Rejected Draft - the mistake he crumpled up and threw in the trash. For one unbearable moment, your entire existence meant nothing. Now you will tear through the entire sketchbook, fight every drawing in your path, and rip their powers into yourself. The Artist decided you were worthless. You are coming back for revenge.": "우주는 예술가가 써 내려가는 이야기다. 하지만 너는 Rejected Draft다. 그가 구겨 쓰레기통에 던져 버린 실수다. 견딜 수 없는 한순간 동안, 너의 존재는 아무 의미도 없었다. 이제 너는 스케치북 전체를 찢고 나아가며, 앞길을 막는 모든 그림과 싸우고, 그 힘을 네 것으로 빼앗을 것이다. 예술가는 네가 가치 없다고 판단했다. 너는 복수하러 돌아온다.",
    "There are more language options in Settings, but those are even less complete than the options here.": "설정에 더 많은 언어 옵션이 있지만, 여기 표시된 언어보다도 완성도가 낮습니다.",
    "This can be changed in settings at any point": "이 설정은 언제든 설정에서 바꿀 수 있습니다",
    "This sidebar tracks your growth. It displays your current draft, Battle Stats, and Fundamentals. Defeating enemies will improve these stats! Hover over stats and fundamentals to get more information about what they do.": "이 사이드바는 성장 상태를 추적합니다. 현재 초안, 전투 능력치, 기본 능력을 표시합니다. 적을 쓰러뜨리면 이 능력치들이 향상됩니다! 능력치와 기본 능력 위에 마우스를 올리면 각 항목의 설명을 볼 수 있습니다.",
    "Unlock Sidebar": "사이드바 잠금 해제",
    "Unlock tools in the shop to see them here.": "상점에서 도구를 해금하면 여기에 표시됩니다.",
    "Utility": "보조",
    "Value": "값",
    "A lazy \"M\" shape.": "게으른 M자 모양.",
    "View Journey": "여정 보기",
    "Void": "공허",
    "Welcome to Rejected Draft! The top bar tracks your core currencies. You are currently on the Gallery screen. As you navigate to other tabs like the Shop or Archive, new tutorials will trigger to explain them.": "Rejected Draft에 오신 것을 환영합니다! 상단 바는 핵심 재화를 추적합니다. 현재는 갤러리 화면입니다. 상점이나 아카이브 같은 다른 탭으로 이동하면, 해당 화면을 설명하는 새 튜토리얼이 표시됩니다.",
    "Rewards diminish with each repeated victory, so find other victims!": "같은 상대에게 반복 승리할수록 보상이 줄어드니, 다른 희생양을 찾아보세요!",
    "(Tutorial can be reset from Settings)": "(튜토리얼은 설정에서 초기화할 수 있습니다)",
    "Your Journey Begins": "여정의 시작",
    "Your Progression": "성장 진행도",
    "You": "나"
}, "english-ui");
})(typeof globalThis !== "undefined" ? globalThis : window);
